// Travel-ID i18n catalog
// Languages (7): en (default), id (Bahasa Indonesia), ms (Bahasa Melayu),
//                ko (한국어), zh (简体中文), ja (日本語), ar (العربية, RTL)
// Categories: beach, temple, cultural, volcano, nature, diving, food, cafe,
//             shopping, nightlife, mosque, museum, adventure, wellness
// Regions:
//   Indonesia — Bali, Jakarta, Yogyakarta, Bandung, Lombok, Komodo, Surabaya,
//               Medan, Bromo, Borobudur, Raja Ampat, Sumatra, Sulawesi, Kalimantan
//   Malaysia  — Kuala Lumpur, Penang, Langkawi, Melaka, Sabah, Sarawak,
//               Cameron Highlands, Johor Bahru, Ipoh, Putrajaya

const translations = {
  en: {
    "common.tagline": "Travel-ID",

    "seo.title": "Travel-ID — Discover Indonesia & Malaysia | Beyond Bali & KL",
    "seo.description": "Discover the best travel spots across Indonesia and Malaysia. Bali, Yogyakarta, Komodo, Bromo, Kuala Lumpur, Penang, Langkawi, Borneo and beyond — halal-friendly, AI trip planning.",
    "seo.keywords": "Indonesia travel, Malaysia travel, Bali, Yogyakarta, Borobudur, Komodo, Mt Bromo, Raja Ampat, Lombok, Kuala Lumpur travel, Penang, Langkawi, Melaka, Cameron Highlands, Sabah, Sarawak, halal travel SEA, Muslim friendly, AI trip planner",

    "nav.home": "Home",
    "nav.explore": "Explore",
    "nav.lang": "Bahasa",

    "app.title": "Discover Indonesia & Malaysia",
    "app.subtitle": "Travel spots recommended by the community",
    "app.searchPh": "Search places...",
    "app.catAll": "All",
    "app.catBeach": "Beach",
    "app.catTemple": "Temple",
    "app.catCultural": "Cultural",
    "app.catVolcano": "Volcano",
    "app.catNature": "Nature",
    "app.catDiving": "Diving",
    "app.catFood": "Food",
    "app.catCafe": "Cafe",
    "app.catShopping": "Shopping",
    "app.catNightlife": "Nightlife",
    "app.catMuseum": "Museum",
    "app.catAdventure": "Adventure",
    "app.catWellness": "Wellness",
    "app.catHalal": "Halal Food",
    "app.catMosque": "Mosque / Prayer Room",
    "app.catVegetarian": "Vegetarian",
    "app.muslimToggle": "Muslim Friendly",
    "app.muslimDesc": "+ Halal restaurants & prayer rooms (musholla / surau) included",

    "prefs.title": "Travel Settings",
    "prefs.dietary": "Preferences",
    "prefs.muslim": "Muslim Friendly",
    "prefs.vegan": "Vegan",
    "prefs.visitType": "Visit Type",
    "prefs.local": "Local Resident (ID/MY)",
    "prefs.firstVisit": "First Visit (international)",
    "prefs.returnVisit": "Return Visit (international)",
    "prefs.business": "Business Trip",
    "prefs.group": "Group Travel",
    "prefs.apply": "Apply",

    "guide.btn": "How to Use",
    "guide.title": "How to Use Travel-ID",
    "guide.step1Title": "Browse Spots",
    "guide.step1Desc": "Explore travel spots across Indonesia and Malaysia recommended by fellow travelers. Filter by category (Beach, Temple, Volcano, …) and region (Bali, KL, Penang, Komodo, …).",
    "guide.step2Title": "Travel Settings",
    "guide.step2Desc": "Tap the gear icon to set your dietary preferences (Muslim Friendly, Vegan) and visit type. These shape what shows on the map and what the AI planner recommends.",
    "guide.step3Title": "View Spot Details",
    "guide.step3Desc": "Tap any spot to see photos, description, address, halal/prayer-room flags, and entry fees. Open directions in Google Maps with one tap.",
    "guide.step4Title": "Switch Map & List",
    "guide.step4Desc": "On mobile, use the Map/List button at the bottom. On desktop, both views are shown side by side.",
    "guide.step5Title": "Save & Bookmark",
    "guide.step5Desc": "Sign in with Google to bookmark spots as 'Want to Visit' or 'Interested'. Saved spots appear in My Spots and feed the AI planner.",
    "guide.step6Title": "AI Trip Planner",
    "guide.step6Desc": "After saving spots, open Plan Trip from the menu. Pick duration, budget, style — the AI builds a day-by-day itinerary including inter-island/cross-border transport (ferry, flight, KTM ETS) and meal suggestions.",
    "guide.dontShowAgain": "Don't show again",
    "guide.dontShowToday": "Don't show today",

    "about.btn": "About",
    "about.title": "About Travel-ID",
    "about.privacy": "Privacy Policy",
    "about.terms": "Terms of Service",
    "about.koinfo": "",

    "app.viewMap": "Map",
    "app.viewList": "List",
    "app.regionAll": "All Regions",
    "app.regionBali": "Bali",
    "app.regionJakarta": "Jakarta",
    "app.regionYogyakarta": "Yogyakarta",
    "app.regionBandung": "Bandung",
    "app.regionLombok": "Lombok",
    "app.regionKomodo": "Komodo",
    "app.regionSurabaya": "Surabaya",
    "app.regionMedan": "Medan",
    "app.regionBromo": "Bromo",
    "app.regionBorobudur": "Borobudur",
    "app.regionRajaAmpat": "Raja Ampat",
    "app.regionSumatra": "Sumatra",
    "app.regionSulawesi": "Sulawesi",
    "app.regionKalimantan": "Kalimantan",
    "app.regionKL": "Kuala Lumpur",
    "app.regionPenang": "Penang",
    "app.regionLangkawi": "Langkawi",
    "app.regionMelaka": "Melaka",
    "app.regionSabah": "Sabah (Borneo)",
    "app.regionSarawak": "Sarawak (Borneo)",
    "app.regionCameron": "Cameron Highlands",
    "app.regionJohor": "Johor Bahru",
    "app.regionIpoh": "Ipoh",
    "app.regionPutrajaya": "Putrajaya",
    "app.regionOther": "Other",

    "app.featured": "Featured",
    "app.rating": "Rating",
    "app.views": "Views",
    "app.noResults": "No spots found. Try a different filter.",
    "app.loading": "Loading spots...",
    "app.loadMore": "Load More",
    "app.openGoogle": "Open in Google Maps",
    "app.mapGoogle": "Google Maps",
    "app.website": "Official Website",
    "app.openingHours": "Opening Hours",
    "app.entryFee": "Entry Fee",
    "app.entryFeeFree": "Free",
    "app.bestTime": "Best Time to Visit",
    "app.localTips": "Local Tips",
    "app.halalBadge": "Halal",
    "app.prayerRoomBadge": "Prayer Room",
    "app.checkBusy": "Check busy times on Google Maps",
    "app.shareSpot": "Share a Spot",
    "app.submitTitle": "Share an Indonesia / Malaysia Travel Spot",
    "app.submitNotice": "Recommend a great spot to fellow travelers. Your submission will appear after admin review.",
    "app.placeLabel": "Place Name",
    "app.placePh": "e.g. Petronas Twin Towers / Tegallalang",
    "app.categoryLabel": "Category",
    "app.descLabel": "Your Review",
    "app.descPh": "Share your experience...",
    "app.addressLabel": "Address",
    "app.addressPh": "Search address...",
    "app.searchBtn": "Search",
    "app.instagramLabel": "Instagram Tags",
    "app.instagramPh": "@username or #hashtag",
    "app.authorLabel": "Your Name",
    "app.authorPh": "Your name",
    "app.cancelBtn": "Cancel",
    "app.submitBtn": "Submit",
    "app.submitted": "Thank you! Your spot will appear after admin review.",
    "app.submitError": "Failed to submit. Please try again.",
    "app.mapError": "Map could not be loaded.",

    "auth.signIn": "Sign In",
    "auth.signOut": "Sign Out",
    "auth.signInWith": "Sign in with Google",
    "auth.welcome": "Welcome",

    "bookmark.wantToVisit": "Want to Visit",
    "bookmark.interested": "Interested",
    "bookmark.remove": "Remove",
    "bookmark.saved": "Saved!",
    "bookmark.removed": "Removed",
    "bookmark.loginRequired": "Sign in to save spots",
    "bookmark.mySpots": "My Spots",
    "bookmark.noBookmarks": "No saved spots yet",
    "bookmark.wantToVisitEmpty": "No 'Want to Visit' spots yet",
    "bookmark.interestedEmpty": "No 'Interested' spots yet",

    "planner.title": "AI Travel Planner",
    "planner.desc": "Plan your trip across Indonesia & Malaysia from your saved spots",
    "planner.days": "Trip Duration",
    "planner.daysUnit": "days",
    "planner.budget": "Budget",
    "planner.budgetBudget": "Budget-friendly",
    "planner.budgetModerate": "Moderate",
    "planner.budgetLuxury": "Luxury",
    "planner.style": "Travel Style",
    "planner.styleRelaxed": "Relaxed",
    "planner.styleBalanced": "Balanced",
    "planner.stylePacked": "Packed",
    "planner.spots": "Spots to Include",
    "planner.generate": "Generate Plan",
    "planner.generating": "Creating your travel plan...",
    "planner.result": "Your Travel Plan",
    "planner.retry": "Generate Again",
    "planner.close": "Close",
    "planner.noSpots": "Save spots as 'Want to Visit' first",
    "planner.error": "Failed to generate plan. Please try again.",
    "planner.rateLimit": "Daily limit reached ({limit} plans/day). Try again tomorrow!",
    "planner.remaining": "{n} plans remaining today",
    "planner.btn": "Create AI Travel Plan",
    "planner.btnFromSpot": "Plan with This Spot",
    "planner.targetNote": "AI builds itineraries from your \"Want to Visit\" list only.",
    "planner.save": "Save Plan",
    "planner.saved": "Plan saved!",
    "planner.myPlans": "My Plans",
    "planner.compare": "Compare",
    "planner.comparePlans": "Compare Plans",
    "planner.noSavedPlans": "No saved plans yet",
    "planner.deletePlan": "Delete",
    "planner.viewPlan": "View",
    "planner.planTitle": "{days}-Day Trip",
    "planner.spots_count": "{n} spots",
    "planner.savedLocal": "Saved on this device",
    "planner.selectToCompare": "Select 2-3 plans to compare",
    "planner.back": "Back",
    "planner.namePrompt": "Name this plan:",
    "planner.share": "Share",
    "planner.shareTitle": "Share this plan",
    "planner.copyLink": "Copy Link",
    "planner.sharing": "Creating share link...",

    "tips.btn": "SEA Travel Tips",
    "tips.title": "Indonesia & Malaysia Travel Tips",
    "tips.officialInfo": "Practical guidance for travelers across Indonesia and Malaysia.",
    "tips.visa": "Visa & Entry",
    "tips.visaDesc": "Indonesia: most nationalities get e-VOA (IDR 500,000 / ~USD 35) up to 30 days, extendable once. Pre-apply at molina.imigrasi.go.id. Malaysia: 90 days visa-free for most Western, ASEAN, GCC and East-Asian passports — check imi.gov.my.",
    "tips.transport": "Getting Around",
    "tips.transportInterIsland": "Indonesia: domestic flights (Garuda, Lion, Citilink, Batik) for long hops; Pelni ferry on a budget; speedboat Bali↔Gili/Lombok/Nusa Penida. Malaysia: AirAsia from KLIA2; KTM ETS Penang↔KL↔Singapore; KLIA Ekspres airport train.",
    "tips.transportLocal": "Both countries: Grab is the dominant ride-hail. Indonesia adds Gojek (also food / bike). Malaysia: avoid metered taxis except Bluebird-equivalents.",
    "tips.transportBali": "Bali: scooter rental ~IDR 80k/day. KL/Penang: monorail, MRT, LRT cover the city well — buy a Touch'n Go card.",
    "tips.currency": "Currency & Payment",
    "tips.currencyDesc": "Indonesia: Rupiah (1 USD ≈ IDR 16,000). Malaysia: Ringgit (1 USD ≈ MYR 4.7). E-wallets dominate locally — GoPay/OVO/DANA/QRIS in ID; Touch'n Go eWallet, GrabPay, Boost in MY. Cards accepted in malls/hotels; cash for warungs/mamak/markets.",
    "tips.meals": "Meal Prices (Approximate)",
    "tips.budget": "Budget — IDR 30k / MYR 10",
    "tips.budgetDesc": "Warung, mamak, nasi padang, nasi lemak, hawker centers",
    "tips.moderate": "Moderate — IDR 50–150k / MYR 20–60",
    "tips.moderateDesc": "Mid-range restaurants, cafes, kopitiam, mall food courts",
    "tips.luxury": "Luxury — IDR 200k+ / MYR 100+",
    "tips.luxuryDesc": "Fine dining, beach clubs, hotel restaurants in Bali / KL / Penang",
    "tips.muslim": "For Muslim Travelers",
    "tips.muslimDesc": "Both countries are Muslim-majority. Halal food is the default. Indonesia: prayer rooms (musholla) at malls, gas stations, airports. Malaysia: surau widely available; JAKIM halal certification is the most stringent benchmark in SEA. Friday prayer (12:00) may slow service in non-tourist areas.",
    "tips.weather": "Weather",
    "tips.weatherDesc": "Tropical year-round (26–32°C). Indonesia dry season May–Sep. Malaysia has two monsoons: east-coast (Kuantan, Terengganu, Tioman) Nov–Feb; west-coast (Penang, Langkawi) milder. Sunrise hikes (Bromo, Rinjani, Kinabalu) need warm layers — temperatures drop below 5°C.",
    "tips.useful": "Useful Tips",
    "tips.bargain": "Bargaining is expected at traditional markets in both countries — start at 30–50% of asking price.",
    "tips.water": "Drink only bottled or filtered water. Tap water in MY is treated but locals still boil/filter.",
    "tips.modesty": "Cover shoulders and knees at temples and mosques. Sarong loaned at most temple entrances.",
    "tips.tipping": "Tipping is not customary. MY adds 6% SST + 10% service charge; ID adds 11% PPN.",
    "tips.simcard": "Indonesia: Telkomsel / XL at airport (IDR 100k for 20GB / 30 days). Malaysia: Maxis Hotlink, Celcom XPax, Digi (MYR 30–50 for 30 days). Passport required at registration.",
    "tips.emergency": "Indonesia: 112 (general) / 110 (police) / 118 (ambulance). Malaysia: 999 (all emergencies) / 994 (fire) / 991 (civil defense).",
    "tips.tourist": "Tourist Police — Indonesia Bali: +62-361-754-599. Malaysia: 03-2149-6590 (Tourist Police KL).",
    "tips.lastUpdated": "Information current as of 2026 · Sources: Indonesian Ministry of Tourism, Tourism Malaysia, official airline sites",

    "footer.text": "© 2026 Travel-ID. All rights reserved.",
    "footer.privacy": "Privacy Policy",
    "footer.terms": "Terms of Service",
  },

  id: {
    "common.tagline": "Travel-ID",

    "seo.title": "Travel-ID — Jelajahi Indonesia & Malaysia | Beyond Bali & KL",
    "seo.description": "Temukan tempat wisata terbaik di Indonesia dan Malaysia. Bali, Yogyakarta, Komodo, Bromo, Kuala Lumpur, Penang, Langkawi, Borneo dan banyak lagi — info halal, perencana perjalanan AI.",
    "seo.keywords": "wisata Indonesia, wisata Malaysia, Bali, Yogyakarta, Borobudur, Komodo, Bromo, Raja Ampat, Lombok, Kuala Lumpur, Penang, Langkawi, Melaka, Sabah, Sarawak, kuliner halal, perencana perjalanan AI",

    "nav.home": "Beranda",
    "nav.explore": "Jelajahi",
    "nav.lang": "English",

    "app.title": "Jelajahi Indonesia & Malaysia",
    "app.subtitle": "Tempat wisata yang direkomendasikan komunitas",
    "app.searchPh": "Cari tempat...",
    "app.catAll": "Semua",
    "app.catBeach": "Pantai",
    "app.catTemple": "Candi/Pura/Kuil",
    "app.catCultural": "Budaya",
    "app.catVolcano": "Gunung Berapi",
    "app.catNature": "Alam",
    "app.catDiving": "Diving",
    "app.catFood": "Kuliner",
    "app.catCafe": "Kafe",
    "app.catShopping": "Belanja",
    "app.catNightlife": "Hiburan Malam",
    "app.catMuseum": "Museum",
    "app.catAdventure": "Petualangan",
    "app.catWellness": "Wellness",
    "app.catHalal": "Kuliner Halal",
    "app.catMosque": "Masjid / Mushola / Surau",
    "app.catVegetarian": "Vegetarian",
    "app.muslimToggle": "Ramah Muslim",
    "app.muslimDesc": "+ Restoran halal & mushola/surau disertakan",

    "prefs.title": "Pengaturan Perjalanan",
    "prefs.dietary": "Preferensi",
    "prefs.muslim": "Ramah Muslim",
    "prefs.vegan": "Vegan",
    "prefs.visitType": "Jenis Kunjungan",
    "prefs.local": "Warga Lokal (ID/MY)",
    "prefs.firstVisit": "Kunjungan Pertama (internasional)",
    "prefs.returnVisit": "Kunjungan Ulang (internasional)",
    "prefs.business": "Perjalanan Bisnis",
    "prefs.group": "Wisata Grup",
    "prefs.apply": "Terapkan",

    "guide.btn": "Cara Pakai",
    "guide.title": "Cara Menggunakan Travel-ID",
    "guide.step1Title": "Jelajah Tempat",
    "guide.step1Desc": "Telusuri tempat wisata di Indonesia dan Malaysia yang direkomendasikan traveler. Filter berdasarkan kategori (Pantai, Candi, dll.) dan wilayah (Bali, KL, Penang, Komodo, …).",
    "guide.step2Title": "Pengaturan Perjalanan",
    "guide.step2Desc": "Tap ikon roda gigi untuk mengatur preferensi diet (Ramah Muslim, Vegan) dan jenis kunjungan. Memengaruhi rekomendasi peta dan AI planner.",
    "guide.step3Title": "Lihat Detail",
    "guide.step3Desc": "Tap tempat untuk melihat foto, deskripsi, alamat, info halal/mushola, dan harga tiket. Buka petunjuk arah di Google Maps dengan satu tap.",
    "guide.step4Title": "Peta & Daftar",
    "guide.step4Desc": "Di mobile, gunakan tombol Peta/Daftar di bawah. Di desktop, keduanya tampil bersebelahan.",
    "guide.step5Title": "Simpan & Bookmark",
    "guide.step5Desc": "Masuk dengan Google untuk menyimpan tempat sebagai 'Ingin Dikunjungi' atau 'Tertarik'. Tempat tersimpan muncul di tab My Spots.",
    "guide.step6Title": "AI Trip Planner",
    "guide.step6Desc": "Setelah menyimpan tempat, buka Plan Trip dari menu. Pilih durasi, budget, gaya — AI menyusun itinerary harian termasuk transportasi antar-pulau/lintas-negara dan saran makanan.",
    "guide.dontShowAgain": "Jangan tampilkan lagi",
    "guide.dontShowToday": "Jangan tampilkan hari ini",

    "about.btn": "Tentang",
    "about.title": "Tentang Travel-ID",
    "about.privacy": "Kebijakan Privasi",
    "about.terms": "Syarat Layanan",
    "about.koinfo": "",

    "app.viewMap": "Peta",
    "app.viewList": "Daftar",
    "app.regionAll": "Semua Wilayah",
    "app.regionBali": "Bali",
    "app.regionJakarta": "Jakarta",
    "app.regionYogyakarta": "Yogyakarta",
    "app.regionBandung": "Bandung",
    "app.regionLombok": "Lombok",
    "app.regionKomodo": "Komodo",
    "app.regionSurabaya": "Surabaya",
    "app.regionMedan": "Medan",
    "app.regionBromo": "Bromo",
    "app.regionBorobudur": "Borobudur",
    "app.regionRajaAmpat": "Raja Ampat",
    "app.regionSumatra": "Sumatera",
    "app.regionSulawesi": "Sulawesi",
    "app.regionKalimantan": "Kalimantan",
    "app.regionKL": "Kuala Lumpur",
    "app.regionPenang": "Penang",
    "app.regionLangkawi": "Langkawi",
    "app.regionMelaka": "Melaka",
    "app.regionSabah": "Sabah (Borneo)",
    "app.regionSarawak": "Sarawak (Borneo)",
    "app.regionCameron": "Cameron Highlands",
    "app.regionJohor": "Johor Bahru",
    "app.regionIpoh": "Ipoh",
    "app.regionPutrajaya": "Putrajaya",
    "app.regionOther": "Lainnya",

    "app.featured": "Pilihan",
    "app.rating": "Rating",
    "app.views": "Dilihat",
    "app.noResults": "Tidak ada hasil. Coba filter lain.",
    "app.loading": "Memuat...",
    "app.loadMore": "Muat Lebih Banyak",
    "app.openGoogle": "Buka di Google Maps",
    "app.mapGoogle": "Google Maps",
    "app.website": "Situs Resmi",
    "app.openingHours": "Jam Buka",
    "app.entryFee": "Harga Tiket",
    "app.entryFeeFree": "Gratis",
    "app.bestTime": "Waktu Terbaik",
    "app.localTips": "Tips Lokal",
    "app.halalBadge": "Halal",
    "app.prayerRoomBadge": "Mushola",
    "app.checkBusy": "Cek waktu ramai di Google Maps",
    "app.shareSpot": "Bagikan Tempat",
    "app.submitTitle": "Bagikan Tempat Wisata Indonesia / Malaysia",
    "app.submitNotice": "Rekomendasikan tempat wisata kepada traveler lain. Akan tampil setelah review admin.",
    "app.placeLabel": "Nama Tempat",
    "app.placePh": "contoh: Petronas Twin Towers / Tegallalang",
    "app.categoryLabel": "Kategori",
    "app.descLabel": "Ulasan Anda",
    "app.descPh": "Bagikan pengalaman Anda...",
    "app.addressLabel": "Alamat",
    "app.addressPh": "Cari alamat...",
    "app.searchBtn": "Cari",
    "app.instagramLabel": "Tag Instagram",
    "app.instagramPh": "@username atau #hashtag",
    "app.authorLabel": "Nama Anda",
    "app.authorPh": "Nama",
    "app.cancelBtn": "Batal",
    "app.submitBtn": "Kirim",
    "app.submitted": "Terima kasih! Akan tampil setelah review admin.",
    "app.submitError": "Gagal mengirim. Coba lagi.",
    "app.mapError": "Peta tidak dapat dimuat.",

    "auth.signIn": "Masuk",
    "auth.signOut": "Keluar",
    "auth.signInWith": "Masuk dengan Google",
    "auth.welcome": "Selamat datang",

    "bookmark.wantToVisit": "Ingin Dikunjungi",
    "bookmark.interested": "Tertarik",
    "bookmark.remove": "Hapus",
    "bookmark.saved": "Tersimpan!",
    "bookmark.removed": "Dihapus",
    "bookmark.loginRequired": "Masuk untuk menyimpan tempat",
    "bookmark.mySpots": "My Spots",
    "bookmark.noBookmarks": "Belum ada tempat tersimpan",
    "bookmark.wantToVisitEmpty": "Belum ada 'Ingin Dikunjungi'",
    "bookmark.interestedEmpty": "Belum ada 'Tertarik'",

    "planner.title": "AI Travel Planner",
    "planner.desc": "Rencanakan perjalanan Anda di Indonesia & Malaysia",
    "planner.days": "Durasi Perjalanan",
    "planner.daysUnit": "hari",
    "planner.budget": "Budget",
    "planner.budgetBudget": "Hemat",
    "planner.budgetModerate": "Sedang",
    "planner.budgetLuxury": "Mewah",
    "planner.style": "Gaya Perjalanan",
    "planner.styleRelaxed": "Santai",
    "planner.styleBalanced": "Seimbang",
    "planner.stylePacked": "Padat",
    "planner.spots": "Tempat",
    "planner.generate": "Buat Rencana",
    "planner.generating": "Membuat rencana perjalanan...",
    "planner.result": "Rencana Perjalanan Anda",
    "planner.retry": "Buat Ulang",
    "planner.close": "Tutup",
    "planner.noSpots": "Simpan tempat sebagai 'Ingin Dikunjungi' dulu",
    "planner.error": "Gagal membuat rencana. Coba lagi.",
    "planner.rateLimit": "Batas harian tercapai ({limit} rencana/hari).",
    "planner.remaining": "Sisa {n} rencana hari ini",
    "planner.btn": "Buat Rencana AI",
    "planner.btnFromSpot": "Rencanakan dengan Tempat Ini",
    "planner.targetNote": "AI hanya membuat rencana dari daftar \"Ingin Dikunjungi\".",
    "planner.save": "Simpan Rencana",
    "planner.saved": "Rencana tersimpan!",
    "planner.myPlans": "Rencana Saya",
    "planner.compare": "Bandingkan",
    "planner.comparePlans": "Bandingkan Rencana",
    "planner.noSavedPlans": "Belum ada rencana tersimpan",
    "planner.deletePlan": "Hapus",
    "planner.viewPlan": "Lihat",
    "planner.planTitle": "Trip {days} Hari",
    "planner.spots_count": "{n} tempat",
    "planner.savedLocal": "Tersimpan di perangkat ini",
    "planner.selectToCompare": "Pilih 2-3 rencana untuk dibandingkan",
    "planner.back": "Kembali",
    "planner.namePrompt": "Beri nama rencana:",
    "planner.share": "Bagikan",
    "planner.shareTitle": "Bagikan rencana ini",
    "planner.copyLink": "Salin Link",
    "planner.sharing": "Membuat link...",

    "tips.btn": "Tips Wisata SEA",
    "tips.title": "Tips Wisata Indonesia & Malaysia",
    "tips.officialInfo": "Panduan praktis untuk wisatawan di Indonesia dan Malaysia.",
    "tips.visa": "Visa & Imigrasi",
    "tips.visaDesc": "Indonesia: e-VOA (IDR 500.000) hingga 30 hari, perpanjangan sekali. Malaysia: bebas visa 90 hari untuk paspor ASEAN, GCC, dan banyak negara Eropa/Asia Timur — cek imi.gov.my.",
    "tips.transport": "Transportasi",
    "tips.transportInterIsland": "ID: penerbangan domestik / Pelni / speedboat antar pulau. MY: AirAsia, KTM ETS Penang↔KL↔Singapore, KLIA Ekspres.",
    "tips.transportLocal": "Kedua negara: Grab dominan. ID juga punya Gojek. Hindari taksi argo non-resmi di MY (gunakan Bluebird ekuivalen).",
    "tips.transportBali": "Bali: sewa motor ~Rp 80rb/hari. KL/Penang: monorail, MRT, LRT — beli kartu Touch'n Go.",
    "tips.currency": "Mata Uang & Pembayaran",
    "tips.currencyDesc": "ID: Rupiah. MY: Ringgit (1 USD ≈ MYR 4,7). E-wallet dominan lokal — GoPay/OVO/DANA/QRIS di ID; Touch'n Go eWallet, GrabPay, Boost di MY. Kartu di mall/hotel.",
    "tips.meals": "Harga Makanan (Perkiraan)",
    "tips.budget": "Hemat — Rp 30rb / RM 10",
    "tips.budgetDesc": "Warung, mamak, padang, nasi lemak, hawker",
    "tips.moderate": "Sedang — Rp 50–150rb / RM 20–60",
    "tips.moderateDesc": "Restoran menengah, kafe, kopitiam, food court",
    "tips.luxury": "Mewah — Rp 200rb+ / RM 100+",
    "tips.luxuryDesc": "Fine dining, beach club, restoran hotel di Bali / KL / Penang",
    "tips.muslim": "Untuk Wisatawan Muslim",
    "tips.muslimDesc": "Kedua negara mayoritas Muslim. Halal default. ID: mushola di mall, SPBU, bandara. MY: surau di mana-mana; sertifikat halal JAKIM adalah standar paling ketat di SEA.",
    "tips.weather": "Cuaca",
    "tips.weatherDesc": "Tropis sepanjang tahun (26–32°C). ID musim kemarau Mei–Sep. MY: monsun pantai timur Nov–Feb; pantai barat (Penang/Langkawi) lebih ringan. Pendakian sunrise (Bromo, Rinjani, Kinabalu) butuh pakaian hangat.",
    "tips.useful": "Tips Berguna",
    "tips.bargain": "Tawar-menawar lazim di pasar tradisional kedua negara — mulai 30–50% harga awal.",
    "tips.water": "Minum air kemasan/filter saja. Air keran MY diolah tapi lokal tetap rebus.",
    "tips.modesty": "Tutupi bahu/lutut di pura/masjid. Sarung disediakan di pintu masuk pura.",
    "tips.tipping": "Tip tidak wajib. MY tambah 6% SST + 10% service. ID tambah 11% PPN.",
    "tips.simcard": "ID: Telkomsel/XL di bandara (Rp 100rb/20GB·30 hari). MY: Maxis/Celcom/Digi (RM 30–50/30 hari). Bawa paspor.",
    "tips.emergency": "ID: 112 / 110 / 118. MY: 999 (semua) / 994 (kebakaran).",
    "tips.tourist": "Polisi Wisata — Bali: +62-361-754-599. KL: 03-2149-6590.",
    "tips.lastUpdated": "Informasi per 2026 · Sumber: Kementerian Pariwisata RI, Tourism Malaysia",

    "footer.text": "© 2026 Travel-ID. Hak cipta dilindungi.",
    "footer.privacy": "Kebijakan Privasi",
    "footer.terms": "Syarat Layanan",
  },

  ms: {
    "common.tagline": "Travel-ID",

    "seo.title": "Travel-ID — Terokai Malaysia & Indonesia | Lebih dari KL & Bali",
    "seo.description": "Temui destinasi pelancongan terbaik di Malaysia dan Indonesia. Kuala Lumpur, Penang, Langkawi, Borneo, Bali, Yogyakarta, Komodo dan banyak lagi — info halal, perancang perjalanan AI.",
    "seo.keywords": "pelancongan Malaysia, pelancongan Indonesia, Kuala Lumpur, Penang, Langkawi, Melaka, Sabah, Sarawak, Cameron Highlands, Bali, Yogyakarta, Borobudur, makanan halal, perancang AI",

    "nav.home": "Laman Utama",
    "nav.explore": "Terokai",
    "nav.lang": "English",

    "app.title": "Terokai Malaysia & Indonesia",
    "app.subtitle": "Tempat menarik yang dicadangkan komuniti",
    "app.searchPh": "Cari tempat...",
    "app.catAll": "Semua",
    "app.catBeach": "Pantai",
    "app.catTemple": "Tokong/Kuil",
    "app.catCultural": "Budaya",
    "app.catVolcano": "Gunung Berapi",
    "app.catNature": "Alam",
    "app.catDiving": "Menyelam",
    "app.catFood": "Makanan",
    "app.catCafe": "Kafe",
    "app.catShopping": "Membeli-belah",
    "app.catNightlife": "Hidup Malam",
    "app.catMuseum": "Muzium",
    "app.catAdventure": "Pengembaraan",
    "app.catWellness": "Kesihatan",
    "app.catHalal": "Makanan Halal",
    "app.catMosque": "Masjid / Surau",
    "app.catVegetarian": "Vegetarian",
    "app.muslimToggle": "Mesra Muslim",
    "app.muslimDesc": "+ Restoran halal & surau disertakan",

    "prefs.title": "Tetapan Perjalanan",
    "prefs.dietary": "Pilihan",
    "prefs.muslim": "Mesra Muslim",
    "prefs.vegan": "Vegan",
    "prefs.visitType": "Jenis Lawatan",
    "prefs.local": "Penduduk Tempatan (MY/ID)",
    "prefs.firstVisit": "Lawatan Pertama (antarabangsa)",
    "prefs.returnVisit": "Lawatan Ulangan (antarabangsa)",
    "prefs.business": "Perjalanan Perniagaan",
    "prefs.group": "Pelancongan Berkumpulan",
    "prefs.apply": "Guna",

    "guide.btn": "Cara Guna",
    "guide.title": "Cara Menggunakan Travel-ID",
    "guide.step1Title": "Layari Tempat",
    "guide.step1Desc": "Terokai tempat menarik di Malaysia dan Indonesia yang dicadangkan oleh pelancong lain. Tapis mengikut kategori dan wilayah (KL, Penang, Bali, Komodo, …).",
    "guide.step2Title": "Tetapan Perjalanan",
    "guide.step2Desc": "Tekan ikon gear untuk menetapkan pilihan diet (Mesra Muslim, Vegan) dan jenis lawatan. Mempengaruhi cadangan peta dan AI planner.",
    "guide.step3Title": "Lihat Butiran Tempat",
    "guide.step3Desc": "Tekan tempat untuk melihat foto, butiran, alamat, halal/surau, dan harga masuk. Buka arah dalam Google Maps dengan satu tekanan.",
    "guide.step4Title": "Peta & Senarai",
    "guide.step4Desc": "Pada telefon mudah alih, gunakan butang Peta/Senarai di bawah. Pada desktop, kedua-duanya dipaparkan bersebelahan.",
    "guide.step5Title": "Simpan & Tanda Buku",
    "guide.step5Desc": "Log masuk dengan Google untuk menyimpan tempat sebagai 'Ingin Lawat' atau 'Berminat'. Tempat disimpan muncul dalam My Spots.",
    "guide.step6Title": "AI Trip Planner",
    "guide.step6Desc": "Selepas menyimpan tempat, buka Plan Trip dari menu. Pilih tempoh, bajet, gaya — AI membina jadual harian termasuk pengangkutan antara pulau/negara.",
    "guide.dontShowAgain": "Jangan tunjukkan lagi",
    "guide.dontShowToday": "Jangan tunjukkan hari ini",

    "about.btn": "Mengenai",
    "about.title": "Mengenai Travel-ID",
    "about.privacy": "Polisi Privasi",
    "about.terms": "Syarat Perkhidmatan",
    "about.koinfo": "",

    "app.viewMap": "Peta",
    "app.viewList": "Senarai",
    "app.regionAll": "Semua Wilayah",
    "app.regionBali": "Bali",
    "app.regionJakarta": "Jakarta",
    "app.regionYogyakarta": "Yogyakarta",
    "app.regionBandung": "Bandung",
    "app.regionLombok": "Lombok",
    "app.regionKomodo": "Komodo",
    "app.regionSurabaya": "Surabaya",
    "app.regionMedan": "Medan",
    "app.regionBromo": "Bromo",
    "app.regionBorobudur": "Borobudur",
    "app.regionRajaAmpat": "Raja Ampat",
    "app.regionSumatra": "Sumatera",
    "app.regionSulawesi": "Sulawesi",
    "app.regionKalimantan": "Kalimantan",
    "app.regionKL": "Kuala Lumpur",
    "app.regionPenang": "Pulau Pinang",
    "app.regionLangkawi": "Langkawi",
    "app.regionMelaka": "Melaka",
    "app.regionSabah": "Sabah",
    "app.regionSarawak": "Sarawak",
    "app.regionCameron": "Cameron Highlands",
    "app.regionJohor": "Johor Bahru",
    "app.regionIpoh": "Ipoh",
    "app.regionPutrajaya": "Putrajaya",
    "app.regionOther": "Lain-lain",

    "app.featured": "Pilihan",
    "app.rating": "Penilaian",
    "app.views": "Tontonan",
    "app.noResults": "Tiada hasil dijumpai. Cuba penapis lain.",
    "app.loading": "Memuatkan...",
    "app.loadMore": "Muat Lagi",
    "app.openGoogle": "Buka dalam Google Maps",
    "app.mapGoogle": "Google Maps",
    "app.website": "Laman Web Rasmi",
    "app.openingHours": "Waktu Operasi",
    "app.entryFee": "Bayaran Masuk",
    "app.entryFeeFree": "Percuma",
    "app.bestTime": "Masa Terbaik",
    "app.localTips": "Tip Tempatan",
    "app.halalBadge": "Halal",
    "app.prayerRoomBadge": "Surau",
    "app.checkBusy": "Semak waktu sibuk di Google Maps",
    "app.shareSpot": "Kongsi Tempat",
    "app.submitTitle": "Kongsi Tempat Pelancongan Malaysia / Indonesia",
    "app.submitNotice": "Cadangkan tempat menarik kepada pelancong lain. Akan dipaparkan selepas semakan admin.",
    "app.placeLabel": "Nama Tempat",
    "app.placePh": "cth: Petronas Twin Towers / Tegallalang",
    "app.categoryLabel": "Kategori",
    "app.descLabel": "Ulasan Anda",
    "app.descPh": "Kongsi pengalaman anda...",
    "app.addressLabel": "Alamat",
    "app.addressPh": "Cari alamat...",
    "app.searchBtn": "Cari",
    "app.instagramLabel": "Tag Instagram",
    "app.instagramPh": "@username atau #hashtag",
    "app.authorLabel": "Nama Anda",
    "app.authorPh": "Nama",
    "app.cancelBtn": "Batal",
    "app.submitBtn": "Hantar",
    "app.submitted": "Terima kasih! Akan dipaparkan selepas semakan admin.",
    "app.submitError": "Gagal menghantar. Cuba lagi.",
    "app.mapError": "Peta tidak dapat dimuatkan.",

    "auth.signIn": "Log Masuk",
    "auth.signOut": "Log Keluar",
    "auth.signInWith": "Log masuk dengan Google",
    "auth.welcome": "Selamat datang",

    "bookmark.wantToVisit": "Ingin Lawat",
    "bookmark.interested": "Berminat",
    "bookmark.remove": "Buang",
    "bookmark.saved": "Disimpan!",
    "bookmark.removed": "Dibuang",
    "bookmark.loginRequired": "Log masuk untuk menyimpan tempat",
    "bookmark.mySpots": "My Spots",
    "bookmark.noBookmarks": "Belum ada tempat disimpan",
    "bookmark.wantToVisitEmpty": "Belum ada 'Ingin Lawat'",
    "bookmark.interestedEmpty": "Belum ada 'Berminat'",

    "planner.title": "AI Travel Planner",
    "planner.desc": "Rancang perjalanan anda di Malaysia & Indonesia",
    "planner.days": "Tempoh Perjalanan",
    "planner.daysUnit": "hari",
    "planner.budget": "Bajet",
    "planner.budgetBudget": "Jimat",
    "planner.budgetModerate": "Sederhana",
    "planner.budgetLuxury": "Mewah",
    "planner.style": "Gaya Perjalanan",
    "planner.styleRelaxed": "Santai",
    "planner.styleBalanced": "Seimbang",
    "planner.stylePacked": "Padat",
    "planner.spots": "Tempat",
    "planner.generate": "Hasilkan Pelan",
    "planner.generating": "Mencipta pelan perjalanan...",
    "planner.result": "Pelan Perjalanan Anda",
    "planner.retry": "Hasilkan Semula",
    "planner.close": "Tutup",
    "planner.noSpots": "Simpan tempat sebagai 'Ingin Lawat' dahulu",
    "planner.error": "Gagal menghasilkan pelan. Cuba lagi.",
    "planner.rateLimit": "Had harian dicapai ({limit} pelan/hari).",
    "planner.remaining": "Baki {n} pelan hari ini",
    "planner.btn": "Cipta Pelan AI",
    "planner.btnFromSpot": "Rancang dengan Tempat Ini",
    "planner.targetNote": "AI hanya menghasilkan pelan dari senarai \"Ingin Lawat\".",
    "planner.save": "Simpan Pelan",
    "planner.saved": "Pelan disimpan!",
    "planner.myPlans": "Pelan Saya",
    "planner.compare": "Banding",
    "planner.comparePlans": "Bandingkan Pelan",
    "planner.noSavedPlans": "Belum ada pelan disimpan",
    "planner.deletePlan": "Padam",
    "planner.viewPlan": "Lihat",
    "planner.planTitle": "Trip {days} Hari",
    "planner.spots_count": "{n} tempat",
    "planner.savedLocal": "Disimpan pada peranti ini",
    "planner.selectToCompare": "Pilih 2-3 pelan untuk dibandingkan",
    "planner.back": "Kembali",
    "planner.namePrompt": "Namakan pelan:",
    "planner.share": "Kongsi",
    "planner.shareTitle": "Kongsi pelan ini",
    "planner.copyLink": "Salin Pautan",
    "planner.sharing": "Mencipta pautan...",

    "tips.btn": "Tip Pelancongan SEA",
    "tips.title": "Tip Pelancongan Malaysia & Indonesia",
    "tips.officialInfo": "Panduan praktikal untuk pelancong di Malaysia dan Indonesia.",
    "tips.visa": "Visa & Imigresen",
    "tips.visaDesc": "Malaysia: bebas visa 90 hari untuk pemegang pasport ASEAN, GCC dan kebanyakan negara Eropah/Asia Timur. Indonesia: e-VOA (IDR 500,000) hingga 30 hari, boleh dilanjutkan sekali.",
    "tips.transport": "Pengangkutan",
    "tips.transportInterIsland": "MY: AirAsia, KTM ETS Penang↔KL↔Singapore, KLIA Ekspres. ID: penerbangan domestik / Pelni / speedboat antara pulau.",
    "tips.transportLocal": "Kedua-dua negara: Grab dominan. ID juga ada Gojek. Elak teksi meter tidak rasmi.",
    "tips.transportBali": "KL/Penang: monorel, MRT, LRT — beli kad Touch'n Go. Bali: sewa motosikal ~RM 25/hari.",
    "tips.currency": "Mata Wang & Pembayaran",
    "tips.currencyDesc": "MY: Ringgit. ID: Rupiah (1 RM ≈ IDR 3,400). E-dompet dominan tempatan — Touch'n Go eWallet, GrabPay, Boost di MY; GoPay/OVO/DANA/QRIS di ID.",
    "tips.meals": "Harga Makanan (Anggaran)",
    "tips.budget": "Jimat — RM 10 / Rp 30rb",
    "tips.budgetDesc": "Mamak, hawker, warung, nasi padang, nasi lemak",
    "tips.moderate": "Sederhana — RM 20–60 / Rp 50–150rb",
    "tips.moderateDesc": "Restoran sederhana, kopitiam, kafe, food court",
    "tips.luxury": "Mewah — RM 100+ / Rp 200rb+",
    "tips.luxuryDesc": "Fine dining, beach club, restoran hotel KL / Penang / Bali",
    "tips.muslim": "Untuk Pelancong Muslim",
    "tips.muslimDesc": "Kedua-dua negara majoriti Muslim. Halal adalah default. MY: surau di mana-mana; sijil JAKIM adalah piawaian paling ketat di SEA. ID: musholla di mall, stesen minyak, lapangan terbang.",
    "tips.weather": "Cuaca",
    "tips.weatherDesc": "Tropika sepanjang tahun (26–32°C). MY: monsun pantai timur Nov–Feb; pantai barat (Penang/Langkawi) lebih lembut. ID: musim kering Mei–Sep. Pendakian subuh (Kinabalu, Bromo, Rinjani) perlu pakaian panas.",
    "tips.useful": "Tip Berguna",
    "tips.bargain": "Tawar-menawar biasa di pasar tradisional kedua-dua negara — mula dari 30–50% harga asal.",
    "tips.water": "Minum hanya air botol atau ditapis. Air paip MY diolah tapi orang tempatan masih rebus.",
    "tips.modesty": "Tutup bahu dan lutut di tokong/masjid. Sarung disediakan di pintu masuk tokong/kuil.",
    "tips.tipping": "Tip tidak wajib. MY: 6% SST + 10% caj khidmat. ID: 11% PPN.",
    "tips.simcard": "MY: Maxis/Celcom/Digi (RM 30–50/30 hari). ID: Telkomsel/XL di lapangan terbang (RM 30 untuk 20GB·30 hari). Bawa pasport.",
    "tips.emergency": "MY: 999 (semua) / 994 (bomba). ID: 112 / 110 (polis) / 118 (ambulans).",
    "tips.tourist": "Polis Pelancong — KL: 03-2149-6590. Bali: +62-361-754-599.",
    "tips.lastUpdated": "Maklumat sehingga 2026 · Sumber: Tourism Malaysia, Kementerian Pelancongan RI",

    "footer.text": "© 2026 Travel-ID. Hak cipta terpelihara.",
    "footer.privacy": "Polisi Privasi",
    "footer.terms": "Syarat Perkhidmatan",
  },

  ko: {
    "common.tagline": "Travel-ID",

    "seo.title": "Travel-ID — 인도네시아 & 말레이시아 여행 가이드 | 발리·KL부터 라자암팟까지",
    "seo.description": "커뮤니티가 추천하는 인도네시아·말레이시아 최고의 여행지. 발리, 족자카르타, 코모도, 쿠알라룸푸르, 페낭, 랑카위, 보르네오 — 할랄 식당과 기도실 정보, AI 여행 플래너 포함.",
    "seo.keywords": "인도네시아 여행, 말레이시아 여행, 발리 여행, 쿠알라룸푸르 여행, 페낭, 랑카위, 코타키나발루, 보르네오, 코모도, 보로부두르, 무슬림 친화 동남아, 할랄 여행, AI 여행 플래너",

    "nav.home": "홈",
    "nav.explore": "탐색",
    "nav.lang": "Bahasa",

    "app.title": "인도네시아 & 말레이시아 발견하기",
    "app.subtitle": "커뮤니티가 추천하는 여행지",
    "app.searchPh": "장소 검색...",
    "app.catAll": "전체",
    "app.catBeach": "해변",
    "app.catTemple": "사원",
    "app.catCultural": "문화",
    "app.catVolcano": "화산",
    "app.catNature": "자연",
    "app.catDiving": "다이빙",
    "app.catFood": "맛집",
    "app.catCafe": "카페",
    "app.catShopping": "쇼핑",
    "app.catNightlife": "나이트라이프",
    "app.catMuseum": "박물관",
    "app.catAdventure": "액티비티",
    "app.catWellness": "웰니스",
    "app.catHalal": "할랄 음식",
    "app.catMosque": "모스크/기도실",
    "app.catVegetarian": "채식",
    "app.muslimToggle": "무슬림 친화",
    "app.muslimDesc": "+ 할랄 식당 & 기도실(무솔라/수라우) 포함",

    "prefs.title": "여행 설정",
    "prefs.dietary": "선호도",
    "prefs.muslim": "무슬림 친화",
    "prefs.vegan": "비건",
    "prefs.visitType": "방문 유형",
    "prefs.local": "현지 거주자 (인니/말레이)",
    "prefs.firstVisit": "첫 방문 (외국인)",
    "prefs.returnVisit": "재방문 (외국인)",
    "prefs.business": "출장",
    "prefs.group": "그룹 여행",
    "prefs.apply": "적용",

    "guide.btn": "사용법",
    "guide.title": "Travel-ID 사용법",
    "guide.step1Title": "장소 둘러보기",
    "guide.step1Desc": "인도네시아·말레이시아 추천 여행지를 탐색하세요. 카테고리(해변/사원/화산 등)와 지역(발리/KL/페낭/코모도 등)으로 필터링.",
    "guide.step2Title": "여행 설정",
    "guide.step2Desc": "톱니바퀴 아이콘으로 식이 선호와 방문 유형을 설정. 지도 표시와 AI 플래너 추천에 반영됩니다.",
    "guide.step3Title": "장소 상세",
    "guide.step3Desc": "장소를 탭하면 사진, 설명, 주소, 할랄/기도실 표시, 입장료를 확인. 구글 지도 길찾기 한 번에 열기.",
    "guide.step4Title": "지도 & 목록",
    "guide.step4Desc": "모바일에서는 하단의 지도/목록 버튼으로 전환. 데스크톱은 나란히 표시.",
    "guide.step5Title": "저장 & 북마크",
    "guide.step5Desc": "Google 로그인 후 '방문할 곳' 또는 '관심 있음'으로 저장. 저장된 장소는 My Spots 탭에 표시되고 AI 플래너의 입력이 됩니다.",
    "guide.step6Title": "AI 여행 플래너",
    "guide.step6Desc": "장소 저장 후 메뉴에서 'Plan Trip'을 여세요. 기간/예산/스타일 선택 시 AI가 섬간·국경간 이동(페리/항공/KTM ETS) 포함 일자별 일정을 만듭니다.",
    "guide.dontShowAgain": "다시 보지 않기",
    "guide.dontShowToday": "오늘 다시 안보기",

    "about.btn": "앱 정보",
    "about.title": "Travel-ID 정보",
    "about.privacy": "개인정보처리방침",
    "about.terms": "이용약관",
    "about.koinfo": "",

    "app.viewMap": "지도",
    "app.viewList": "목록",
    "app.regionAll": "전체 지역",
    "app.regionBali": "발리",
    "app.regionJakarta": "자카르타",
    "app.regionYogyakarta": "족자카르타",
    "app.regionBandung": "반둥",
    "app.regionLombok": "롬복",
    "app.regionKomodo": "코모도",
    "app.regionSurabaya": "수라바야",
    "app.regionMedan": "메단",
    "app.regionBromo": "브로모",
    "app.regionBorobudur": "보로부두르",
    "app.regionRajaAmpat": "라자암팟",
    "app.regionSumatra": "수마트라",
    "app.regionSulawesi": "술라웨시",
    "app.regionKalimantan": "칼리만탄",
    "app.regionKL": "쿠알라룸푸르",
    "app.regionPenang": "페낭",
    "app.regionLangkawi": "랑카위",
    "app.regionMelaka": "말라카",
    "app.regionSabah": "사바 (보르네오)",
    "app.regionSarawak": "사라왁 (보르네오)",
    "app.regionCameron": "카메론 하이랜드",
    "app.regionJohor": "조호바루",
    "app.regionIpoh": "이포",
    "app.regionPutrajaya": "푸트라자야",
    "app.regionOther": "기타",

    "app.featured": "추천",
    "app.rating": "평점",
    "app.views": "조회",
    "app.noResults": "검색 결과가 없습니다. 다른 필터를 시도해 보세요.",
    "app.loading": "불러오는 중...",
    "app.loadMore": "더 보기",
    "app.openGoogle": "구글 지도에서 열기",
    "app.mapGoogle": "구글 지도",
    "app.website": "공식 홈페이지",
    "app.openingHours": "영업시간",
    "app.entryFee": "입장료",
    "app.entryFeeFree": "무료",
    "app.bestTime": "방문 추천 시기",
    "app.localTips": "현지 팁",
    "app.halalBadge": "할랄",
    "app.prayerRoomBadge": "기도실",
    "app.checkBusy": "구글 지도에서 혼잡도 확인",
    "app.shareSpot": "내 장소 등록",
    "app.submitTitle": "인도네시아/말레이시아 여행지 등록",
    "app.submitNotice": "내가 알고 있는 여행지를 다른 여행자에게 공유해주세요. 등록 후 관리자 승인을 거쳐 게시됩니다.",
    "app.placeLabel": "장소 이름",
    "app.placePh": "예: 페트로나스 트윈 타워 / 떼갈랄랑",
    "app.categoryLabel": "카테고리",
    "app.descLabel": "리뷰",
    "app.descPh": "경험을 공유하세요...",
    "app.addressLabel": "주소",
    "app.addressPh": "주소 검색...",
    "app.searchBtn": "검색",
    "app.instagramLabel": "인스타그램 태그",
    "app.instagramPh": "@계정 또는 #해시태그",
    "app.authorLabel": "작성자",
    "app.authorPh": "이름",
    "app.cancelBtn": "취소",
    "app.submitBtn": "제출",
    "app.submitted": "감사합니다! 관리자 승인 후 게시됩니다.",
    "app.submitError": "제출에 실패했습니다. 다시 시도해 주세요.",
    "app.mapError": "지도를 불러올 수 없습니다.",

    "auth.signIn": "로그인",
    "auth.signOut": "로그아웃",
    "auth.signInWith": "Google로 로그인",
    "auth.welcome": "환영합니다",

    "bookmark.wantToVisit": "방문할 곳",
    "bookmark.interested": "관심 있음",
    "bookmark.remove": "삭제",
    "bookmark.saved": "저장됨!",
    "bookmark.removed": "삭제됨",
    "bookmark.loginRequired": "로그인 후 저장 가능",
    "bookmark.mySpots": "My Spots",
    "bookmark.noBookmarks": "저장된 장소가 없습니다",
    "bookmark.wantToVisitEmpty": "'방문할 곳'에 저장된 장소가 없습니다",
    "bookmark.interestedEmpty": "'관심 있음'에 저장된 장소가 없습니다",

    "planner.title": "AI 여행 플래너",
    "planner.desc": "저장한 장소 기반으로 인도네시아·말레이시아 일정을 만들어 드립니다",
    "planner.days": "여행 기간",
    "planner.daysUnit": "일",
    "planner.budget": "예산",
    "planner.budgetBudget": "알뜰",
    "planner.budgetModerate": "보통",
    "planner.budgetLuxury": "럭셔리",
    "planner.style": "여행 스타일",
    "planner.styleRelaxed": "여유롭게",
    "planner.styleBalanced": "균형",
    "planner.stylePacked": "꽉 채워서",
    "planner.spots": "포함할 장소",
    "planner.generate": "일정 만들기",
    "planner.generating": "여행 일정 생성 중...",
    "planner.result": "여행 일정",
    "planner.retry": "다시 만들기",
    "planner.close": "닫기",
    "planner.noSpots": "먼저 '방문할 곳'에 장소를 저장하세요",
    "planner.error": "일정 생성에 실패했습니다.",
    "planner.rateLimit": "오늘 생성 한도({limit}회)에 도달했습니다.",
    "planner.remaining": "오늘 {n}회 남았습니다",
    "planner.btn": "AI 여행 일정 만들기",
    "planner.btnFromSpot": "이 장소로 일정 짜기",
    "planner.targetNote": "AI는 \"방문할 곳\" 목록만으로 일정을 만듭니다.",
    "planner.save": "일정 저장",
    "planner.saved": "일정이 저장되었습니다!",
    "planner.myPlans": "내 일정",
    "planner.compare": "비교",
    "planner.comparePlans": "일정 비교",
    "planner.noSavedPlans": "저장된 일정이 없습니다",
    "planner.deletePlan": "삭제",
    "planner.viewPlan": "보기",
    "planner.planTitle": "{days}일 일정",
    "planner.spots_count": "{n}곳",
    "planner.savedLocal": "이 기기에 저장됨",
    "planner.selectToCompare": "2-3개 일정을 선택하여 비교",
    "planner.back": "뒤로",
    "planner.namePrompt": "일정 이름:",
    "planner.share": "공유",
    "planner.shareTitle": "이 일정 공유하기",
    "planner.copyLink": "링크 복사",
    "planner.sharing": "공유 링크 생성 중...",

    "tips.btn": "동남아 여행 팁",
    "tips.title": "인도네시아 & 말레이시아 여행 팁",
    "tips.officialInfo": "한국인 여행자를 위한 인도네시아·말레이시아 실용 정보.",
    "tips.visa": "비자 & 입국",
    "tips.visaDesc": "인니: 한국 여권 도착비자(e-VOA, IDR 500,000)로 30일 체류, 1회 연장 가능. 말레이: 한국 여권 무비자 90일.",
    "tips.transport": "교통",
    "tips.transportInterIsland": "인니: 국내선(가루다/라이언/시티링크), Pelni 페리, 발리↔길리/롬복/누사페니다 스피드보트. 말레이: 에어아시아, KTM ETS(페낭↔KL↔싱가포르), KLIA Ekspres 공항철도.",
    "tips.transportLocal": "양국 모두: Grab 라이드헤일링이 표준. 인니는 Gojek 추가. 미터 택시는 Bluebird만 신뢰.",
    "tips.transportBali": "발리: 스쿠터 렌트(약 8만 IDR/일). KL/페낭: 모노레일/MRT/LRT — Touch'n Go 카드 구매.",
    "tips.currency": "통화 & 결제",
    "tips.currencyDesc": "인니: 루피아(1 USD ≈ IDR 16,000). 말레이: 링깃(1 USD ≈ MYR 4.7, 100원 ≈ MYR 0.34). 현지 e-wallet — 인니: GoPay/OVO/DANA/QRIS, 말레이: Touch'n Go eWallet/GrabPay/Boost.",
    "tips.meals": "식사 가격(대략)",
    "tips.budget": "알뜰 — IDR 30,000 / MYR 10 (3-4천원)",
    "tips.budgetDesc": "와룽, 마막(Mamak), 빠당, 나시르막, 호커센터",
    "tips.moderate": "보통 — IDR 50-150k / MYR 20-60 (5천-2만원)",
    "tips.moderateDesc": "중급 식당, 코피티암, 카페, 푸드코트",
    "tips.luxury": "럭셔리 — IDR 200k+ / MYR 100+ (3만원+)",
    "tips.luxuryDesc": "파인다이닝, 비치클럽, 발리/KL/페낭 호텔 레스토랑",
    "tips.muslim": "무슬림 여행자",
    "tips.muslimDesc": "양국 모두 무슬림 다수국. 할랄이 기본. 인니: 쇼핑몰/주유소/공항에 무솔라. 말레이: 수라우 어디에나 있고 JAKIM 할랄 인증이 동남아 최고 엄격 기준.",
    "tips.weather": "날씨",
    "tips.weatherDesc": "연중 열대(26~32°C). 인니 건기 5~9월. 말레이는 동해안(콴탄/트렝가누/티오만) 11~2월 우기, 서해안(페낭/랑카위)은 더 온화. 일출 등반(브로모/린자니/키나발루)은 보온 필수.",
    "tips.useful": "유용한 팁",
    "tips.bargain": "양국 재래시장에선 흥정 일반적 — 호가의 30~50%부터 시작.",
    "tips.water": "생수/정수만 마시기. 말레이 수돗물은 정수되지만 현지인도 끓여 마심.",
    "tips.modesty": "사원/모스크 방문 시 어깨와 무릎을 가리세요. 사원 입구에서 사롱 대여.",
    "tips.tipping": "팁 문화 없음. 말레이 청구서: 6% SST + 10% 서비스 차지. 인니: 11% PPN.",
    "tips.simcard": "인니: Telkomsel/XL 공항(IDR 100k/20GB·30일). 말레이: Maxis/Celcom/Digi(RM 30-50/30일). 여권 등록 필요.",
    "tips.emergency": "인니: 112(공통)/110(경찰)/118(구급). 말레이: 999(전체)/994(소방).",
    "tips.tourist": "관광경찰 — 발리: +62-361-754-599. KL: 03-2149-6590.",
    "tips.korean": "주인도네시아 한국대사관: +62-21-2967-2555 (자카르타). 주말레이시아 한국대사관: +60-3-4251-2336 (KL). 영사콜센터(24h): +82-2-3210-0404.",
    "tips.lastUpdated": "정보 기준 2026년 · 출처: 인도네시아 관광부, 말레이시아 관광청, 항공사 공식 사이트",

    "footer.text": "© 2026 Travel-ID. All rights reserved.",
    "footer.privacy": "개인정보처리방침",
    "footer.terms": "이용약관",
  },

  zh: {
    "common.tagline": "Travel-ID",

    "seo.title": "Travel-ID — 探索印度尼西亚与马来西亚 | 巴厘岛、吉隆坡及更多",
    "seo.description": "发现社区推荐的印尼和马来西亚最佳旅游胜地。巴厘岛、日惹、科莫多、吉隆坡、槟城、兰卡威、婆罗洲等 — 含清真餐厅、礼拜室及AI行程规划。",
    "seo.keywords": "印尼旅游, 马来西亚旅游, 巴厘岛, 吉隆坡, 槟城, 兰卡威, 马六甲, 沙巴, 砂拉越, 婆罗洲, 科莫多, 日惹, 婆罗浮屠, 穆斯林友好, AI行程",

    "nav.home": "首页",
    "nav.explore": "探索",
    "nav.lang": "Bahasa",

    "app.title": "探索印尼与马来西亚",
    "app.subtitle": "社区推荐的旅游胜地",
    "app.searchPh": "搜索地点...",
    "app.catAll": "全部",
    "app.catBeach": "海滩",
    "app.catTemple": "寺庙",
    "app.catCultural": "文化",
    "app.catVolcano": "火山",
    "app.catNature": "自然",
    "app.catDiving": "潜水",
    "app.catFood": "美食",
    "app.catCafe": "咖啡馆",
    "app.catShopping": "购物",
    "app.catNightlife": "夜生活",
    "app.catMuseum": "博物馆",
    "app.catAdventure": "探险",
    "app.catWellness": "养生",
    "app.catHalal": "清真美食",
    "app.catMosque": "清真寺/礼拜室",
    "app.catVegetarian": "素食",
    "app.muslimToggle": "穆斯林友好",
    "app.muslimDesc": "+ 包含清真餐厅与祈祷室",

    "prefs.title": "旅行设置",
    "prefs.dietary": "饮食偏好",
    "prefs.muslim": "穆斯林友好",
    "prefs.vegan": "纯素",
    "prefs.visitType": "访问类型",
    "prefs.local": "本地居民(印尼/马来)",
    "prefs.firstVisit": "首次访问(国际)",
    "prefs.returnVisit": "再次访问(国际)",
    "prefs.business": "商务出行",
    "prefs.group": "团体旅行",
    "prefs.apply": "应用",

    "guide.btn": "使用说明",
    "guide.title": "Travel-ID 使用方法",
    "guide.step1Title": "浏览地点",
    "guide.step1Desc": "探索印尼和马来西亚的旅游胜地。可按分类(海滩、寺庙、火山等)和地区(巴厘、吉隆坡、槟城、科莫多等)筛选。",
    "guide.step2Title": "旅行设置",
    "guide.step2Desc": "点击齿轮图标设置饮食偏好和访问类型。这会影响地图显示和AI规划推荐。",
    "guide.step3Title": "查看详情",
    "guide.step3Desc": "点击任意地点查看照片、描述、地址、清真/礼拜室标记及门票费用。一键打开Google地图导航。",
    "guide.step4Title": "地图与列表",
    "guide.step4Desc": "在手机上,使用底部的地图/列表按钮切换。在桌面端,两种视图并排显示。",
    "guide.step5Title": "保存与收藏",
    "guide.step5Desc": "用Google登录可将地点保存为'想去'或'感兴趣'。已保存的地点显示在My Spots标签页。",
    "guide.step6Title": "AI行程规划",
    "guide.step6Desc": "保存地点后,从菜单打开规划行程。选择天数、预算和风格 — AI会生成包含跨岛/跨国交通(轮渡/国内航班/KTM ETS)和餐饮推荐的逐日行程。",
    "guide.dontShowAgain": "不再显示",
    "guide.dontShowToday": "今日不再显示",

    "about.btn": "关于",
    "about.title": "关于 Travel-ID",
    "about.privacy": "隐私政策",
    "about.terms": "服务条款",
    "about.koinfo": "",

    "app.viewMap": "地图",
    "app.viewList": "列表",
    "app.regionAll": "所有地区",
    "app.regionBali": "巴厘岛",
    "app.regionJakarta": "雅加达",
    "app.regionYogyakarta": "日惹",
    "app.regionBandung": "万隆",
    "app.regionLombok": "龙目岛",
    "app.regionKomodo": "科莫多",
    "app.regionSurabaya": "泗水",
    "app.regionMedan": "棉兰",
    "app.regionBromo": "布罗莫",
    "app.regionBorobudur": "婆罗浮屠",
    "app.regionRajaAmpat": "四王群岛",
    "app.regionSumatra": "苏门答腊",
    "app.regionSulawesi": "苏拉威西",
    "app.regionKalimantan": "加里曼丹",
    "app.regionKL": "吉隆坡",
    "app.regionPenang": "槟城",
    "app.regionLangkawi": "兰卡威",
    "app.regionMelaka": "马六甲",
    "app.regionSabah": "沙巴(婆罗洲)",
    "app.regionSarawak": "砂拉越(婆罗洲)",
    "app.regionCameron": "金马伦高原",
    "app.regionJohor": "新山",
    "app.regionIpoh": "怡保",
    "app.regionPutrajaya": "布城",
    "app.regionOther": "其他",

    "app.featured": "推荐",
    "app.rating": "评分",
    "app.views": "浏览",
    "app.noResults": "未找到结果。请尝试其他筛选。",
    "app.loading": "加载中...",
    "app.loadMore": "加载更多",
    "app.openGoogle": "在 Google 地图打开",
    "app.mapGoogle": "Google 地图",
    "app.website": "官方网站",
    "app.openingHours": "营业时间",
    "app.entryFee": "门票",
    "app.entryFeeFree": "免费",
    "app.bestTime": "最佳访问时间",
    "app.localTips": "当地贴士",
    "app.halalBadge": "清真",
    "app.prayerRoomBadge": "礼拜室",
    "app.checkBusy": "在 Google 地图查看忙碌时段",
    "app.shareSpot": "分享地点",
    "app.submitTitle": "分享印尼/马来西亚旅游地点",
    "app.submitNotice": "向其他旅行者推荐你了解的地点。审核通过后将显示。",
    "app.placeLabel": "地点名称",
    "app.placePh": "如:双子塔/德格拉朗梯田",
    "app.categoryLabel": "分类",
    "app.descLabel": "你的评价",
    "app.descPh": "分享你的体验...",
    "app.addressLabel": "地址",
    "app.addressPh": "搜索地址...",
    "app.searchBtn": "搜索",
    "app.instagramLabel": "Instagram 标签",
    "app.instagramPh": "@用户名 或 #话题",
    "app.authorLabel": "你的姓名",
    "app.authorPh": "姓名",
    "app.cancelBtn": "取消",
    "app.submitBtn": "提交",
    "app.submitted": "感谢!审核通过后将显示。",
    "app.submitError": "提交失败,请重试。",
    "app.mapError": "无法加载地图。",

    "auth.signIn": "登录",
    "auth.signOut": "登出",
    "auth.signInWith": "使用 Google 登录",
    "auth.welcome": "欢迎",

    "bookmark.wantToVisit": "想去",
    "bookmark.interested": "感兴趣",
    "bookmark.remove": "移除",
    "bookmark.saved": "已保存!",
    "bookmark.removed": "已移除",
    "bookmark.loginRequired": "请登录后保存",
    "bookmark.mySpots": "My Spots",
    "bookmark.noBookmarks": "暂无收藏",
    "bookmark.wantToVisitEmpty": "暂无'想去'地点",
    "bookmark.interestedEmpty": "暂无'感兴趣'地点",

    "planner.title": "AI 行程规划",
    "planner.desc": "基于已保存地点规划印尼和马来西亚行程",
    "planner.days": "行程天数",
    "planner.daysUnit": "天",
    "planner.budget": "预算",
    "planner.budgetBudget": "经济",
    "planner.budgetModerate": "中等",
    "planner.budgetLuxury": "奢华",
    "planner.style": "旅行风格",
    "planner.styleRelaxed": "悠闲",
    "planner.styleBalanced": "平衡",
    "planner.stylePacked": "紧凑",
    "planner.spots": "包含地点",
    "planner.generate": "生成行程",
    "planner.generating": "正在生成行程...",
    "planner.result": "你的行程",
    "planner.retry": "重新生成",
    "planner.close": "关闭",
    "planner.noSpots": "请先将地点保存为'想去'",
    "planner.error": "生成失败,请重试。",
    "planner.rateLimit": "今日已达上限({limit}次/天)。",
    "planner.remaining": "今日剩余 {n} 次",
    "planner.btn": "创建AI行程",
    "planner.btnFromSpot": "用此地点规划",
    "planner.targetNote": "AI 仅基于你的\"想去\"列表生成行程。",
    "planner.save": "保存行程",
    "planner.saved": "行程已保存!",
    "planner.myPlans": "我的行程",
    "planner.compare": "对比",
    "planner.comparePlans": "对比行程",
    "planner.noSavedPlans": "暂无保存行程",
    "planner.deletePlan": "删除",
    "planner.viewPlan": "查看",
    "planner.planTitle": "{days}天行程",
    "planner.spots_count": "{n}个地点",
    "planner.savedLocal": "已保存到本设备",
    "planner.selectToCompare": "选择 2-3 个行程进行对比",
    "planner.back": "返回",
    "planner.namePrompt": "为行程命名:",
    "planner.share": "分享",
    "planner.shareTitle": "分享此行程",
    "planner.copyLink": "复制链接",
    "planner.sharing": "正在创建分享链接...",

    "tips.btn": "东南亚旅行贴士",
    "tips.title": "印尼 & 马来西亚旅行贴士",
    "tips.officialInfo": "面向中国游客的印尼·马来西亚实用旅行信息。",
    "tips.visa": "签证与入境",
    "tips.visaDesc": "印尼:中国护照可办落地签 e-VOA(IDR 500,000)停留30天,可延期一次。马来西亚:中国护照免签30天(2024起常态化)。",
    "tips.transport": "交通",
    "tips.transportInterIsland": "印尼:国内航班(Garuda/Lion/Citilink/Batik)、Pelni 轮渡、巴厘↔吉利/龙目/努沙佩尼达快艇。马来:亚航、KTM ETS槟城↔吉隆坡↔新加坡、KLIA机场快线。",
    "tips.transportLocal": "两国:Grab 网约车通用。印尼另有 Gojek。市内打表出租避开非Bluebird系列。",
    "tips.transportBali": "巴厘:摩托车租赁(约 IDR 80,000/天)。吉隆坡/槟城:单轨、MRT、LRT覆盖城区 — 买Touch'n Go卡。",
    "tips.currency": "货币与支付",
    "tips.currencyDesc": "印尼盾(1 USD ≈ IDR 16,000)。马币林吉特(1 USD ≈ MYR 4.7,1 RMB ≈ MYR 0.65)。本地电子钱包占主导 — 印尼:GoPay/OVO/DANA/QRIS;马来:Touch'n Go eWallet/GrabPay/Boost。",
    "tips.meals": "餐饮价格(参考)",
    "tips.budget": "经济 — IDR 30k / MYR 10 (¥10-15)",
    "tips.budgetDesc": "Mamak、路边摊、Warung、巴东菜、椰浆饭",
    "tips.moderate": "中等 — IDR 50-150k / MYR 20-60 (¥30-100)",
    "tips.moderateDesc": "中档餐厅、咖啡店、Kopitiam、美食广场",
    "tips.luxury": "奢华 — IDR 200k+ / MYR 100+ (¥150+)",
    "tips.luxuryDesc": "高级餐厅、海滩俱乐部、巴厘/吉隆坡/槟城酒店餐厅",
    "tips.muslim": "穆斯林游客",
    "tips.muslimDesc": "两国均为穆斯林多数国家。清真为默认。马来:Surau随处可见,JAKIM清真认证为东南亚最严标准。印尼:商场、加油站、机场均设musholla。",
    "tips.weather": "天气",
    "tips.weatherDesc": "全年热带气候(26–32°C)。印尼旱季5–9月。马来东海岸11–2月雨季,西海岸(槟城/兰卡威)较温和。日出登山(布罗莫、林贾尼、京那巴鲁)需保暖。",
    "tips.useful": "实用提醒",
    "tips.bargain": "两国传统市场可砍价 — 从开价的30–50%开始还。",
    "tips.water": "只喝瓶装/过滤水。马来自来水经处理但本地人仍煮沸。",
    "tips.modesty": "进入寺庙/清真寺时遮盖肩膀和膝盖。寺庙入口提供纱笼。",
    "tips.tipping": "无小费文化。马来账单加6% SST + 10%服务费。印尼加11% PPN。",
    "tips.simcard": "印尼:机场Telkomsel/XL(IDR 100k / 20GB·30天)。马来:Maxis/Celcom/Digi(RM 30-50 / 30天)。需护照实名。",
    "tips.emergency": "印尼:112/110/118。马来:999(综合)/994(消防)。",
    "tips.tourist": "旅游警察 — 巴厘:+62-361-754-599。吉隆坡:03-2149-6590。",
    "tips.korean": "中国驻印尼大使馆:+62-21-525-1981(雅加达)。中国驻马来西亚大使馆:+60-3-2161-2148(吉隆坡)。",
    "tips.lastUpdated": "信息截至 2026 年 · 来源:印尼旅游部、马来西亚旅游局、各航空公司官方网站",

    "footer.text": "© 2026 Travel-ID. 版权所有。",
    "footer.privacy": "隐私政策",
    "footer.terms": "服务条款",
  },

  ja: {
    "common.tagline": "Travel-ID",

    "seo.title": "Travel-ID — インドネシア&マレーシア旅行ガイド | バリ島・KLから先へ",
    "seo.description": "コミュニティ推薦のインドネシア・マレーシア最高の観光地を発見。バリ島、ジョグジャカルタ、コモド、クアラルンプール、ペナン、ランカウイ、ボルネオ等 — ハラル料理・礼拝室情報、AI旅行プランナー付き。",
    "seo.keywords": "インドネシア旅行, マレーシア旅行, バリ島, ジョグジャカルタ, ボロブドゥール, コモド, クアラルンプール, ペナン, ランカウイ, マラッカ, サバ, サラワク, ボルネオ, ムスリムフレンドリー, AI旅行プランナー",

    "nav.home": "ホーム",
    "nav.explore": "探索",
    "nav.lang": "Bahasa",

    "app.title": "インドネシア&マレーシアを発見しよう",
    "app.subtitle": "コミュニティが推薦する観光地",
    "app.searchPh": "場所を検索...",
    "app.catAll": "すべて",
    "app.catBeach": "ビーチ",
    "app.catTemple": "寺院",
    "app.catCultural": "文化",
    "app.catVolcano": "火山",
    "app.catNature": "自然",
    "app.catDiving": "ダイビング",
    "app.catFood": "グルメ",
    "app.catCafe": "カフェ",
    "app.catShopping": "ショッピング",
    "app.catNightlife": "ナイトライフ",
    "app.catMuseum": "博物館",
    "app.catAdventure": "アドベンチャー",
    "app.catWellness": "ウェルネス",
    "app.catHalal": "ハラルフード",
    "app.catMosque": "モスク/礼拝室",
    "app.catVegetarian": "ベジタリアン",
    "app.muslimToggle": "ムスリムフレンドリー",
    "app.muslimDesc": "+ ハラルレストラン&礼拝室を含む",

    "prefs.title": "旅行設定",
    "prefs.dietary": "好み",
    "prefs.muslim": "ムスリムフレンドリー",
    "prefs.vegan": "ヴィーガン",
    "prefs.visitType": "訪問タイプ",
    "prefs.local": "現地居住者(ID/MY)",
    "prefs.firstVisit": "初訪問(海外から)",
    "prefs.returnVisit": "再訪問(海外から)",
    "prefs.business": "出張",
    "prefs.group": "団体旅行",
    "prefs.apply": "適用",

    "guide.btn": "使い方",
    "guide.title": "Travel-IDの使い方",
    "guide.step1Title": "観光地を見る",
    "guide.step1Desc": "インドネシア・マレーシアの旅行者推薦スポットを探索。カテゴリ(ビーチ・寺院・火山など)と地域(バリ・KL・ペナン・コモドなど)で絞り込めます。",
    "guide.step2Title": "旅行設定",
    "guide.step2Desc": "歯車アイコンで食の好みと訪問タイプを設定。地図表示とAIプランナーの推薦に反映されます。",
    "guide.step3Title": "詳細表示",
    "guide.step3Desc": "スポットをタップで写真、説明、住所、ハラル/礼拝室マーク、入場料を確認。ワンタップでGoogleマップのルート案内を起動。",
    "guide.step4Title": "地図とリスト",
    "guide.step4Desc": "モバイルでは下部の地図/リストボタンで切替。デスクトップでは左右に並んで表示。",
    "guide.step5Title": "保存とブックマーク",
    "guide.step5Desc": "Googleでログインしてスポットを「行きたい」または「興味あり」に保存。My Spotsタブに表示。",
    "guide.step6Title": "AI旅行プランナー",
    "guide.step6Desc": "スポット保存後、メニューからPlan Tripを開く。期間・予算・スタイルを選ぶと、AIが島間/国境間移動(フェリー/国内線/KTM ETS)と食事提案を含む日別プランを作成。",
    "guide.dontShowAgain": "今後表示しない",
    "guide.dontShowToday": "今日は表示しない",

    "about.btn": "アプリについて",
    "about.title": "Travel-ID について",
    "about.privacy": "プライバシーポリシー",
    "about.terms": "利用規約",
    "about.koinfo": "",

    "app.viewMap": "地図",
    "app.viewList": "リスト",
    "app.regionAll": "全地域",
    "app.regionBali": "バリ島",
    "app.regionJakarta": "ジャカルタ",
    "app.regionYogyakarta": "ジョグジャカルタ",
    "app.regionBandung": "バンドン",
    "app.regionLombok": "ロンボク",
    "app.regionKomodo": "コモド",
    "app.regionSurabaya": "スラバヤ",
    "app.regionMedan": "メダン",
    "app.regionBromo": "ブロモ",
    "app.regionBorobudur": "ボロブドゥール",
    "app.regionRajaAmpat": "ラジャアンパット",
    "app.regionSumatra": "スマトラ",
    "app.regionSulawesi": "スラウェシ",
    "app.regionKalimantan": "カリマンタン",
    "app.regionKL": "クアラルンプール",
    "app.regionPenang": "ペナン",
    "app.regionLangkawi": "ランカウイ",
    "app.regionMelaka": "マラッカ",
    "app.regionSabah": "サバ州(ボルネオ)",
    "app.regionSarawak": "サラワク州(ボルネオ)",
    "app.regionCameron": "キャメロン高原",
    "app.regionJohor": "ジョホールバル",
    "app.regionIpoh": "イポー",
    "app.regionPutrajaya": "プトラジャヤ",
    "app.regionOther": "その他",

    "app.featured": "おすすめ",
    "app.rating": "評価",
    "app.views": "閲覧",
    "app.noResults": "該当なし。別のフィルターをお試しください。",
    "app.loading": "読み込み中...",
    "app.loadMore": "さらに読み込む",
    "app.openGoogle": "Google マップで開く",
    "app.mapGoogle": "Google マップ",
    "app.website": "公式サイト",
    "app.openingHours": "営業時間",
    "app.entryFee": "入場料",
    "app.entryFeeFree": "無料",
    "app.bestTime": "ベストシーズン",
    "app.localTips": "現地情報",
    "app.halalBadge": "ハラル",
    "app.prayerRoomBadge": "礼拝室",
    "app.checkBusy": "Google マップで混雑状況を確認",
    "app.shareSpot": "スポットを投稿",
    "app.submitTitle": "インドネシア/マレーシアの観光地を投稿",
    "app.submitNotice": "あなたが知っている素敵なスポットを他の旅行者にシェア。管理者承認後に公開されます。",
    "app.placeLabel": "場所の名前",
    "app.placePh": "例: ペトロナスツインタワー / テガラランの棚田",
    "app.categoryLabel": "カテゴリ",
    "app.descLabel": "あなたのレビュー",
    "app.descPh": "体験を共有してください...",
    "app.addressLabel": "住所",
    "app.addressPh": "住所を検索...",
    "app.searchBtn": "検索",
    "app.instagramLabel": "Instagram タグ",
    "app.instagramPh": "@ユーザー名 または #ハッシュタグ",
    "app.authorLabel": "あなたの名前",
    "app.authorPh": "名前",
    "app.cancelBtn": "キャンセル",
    "app.submitBtn": "送信",
    "app.submitted": "ありがとうございます!管理者承認後に公開されます。",
    "app.submitError": "送信に失敗しました。再度お試しください。",
    "app.mapError": "地図を読み込めませんでした。",

    "auth.signIn": "ログイン",
    "auth.signOut": "ログアウト",
    "auth.signInWith": "Google でログイン",
    "auth.welcome": "ようこそ",

    "bookmark.wantToVisit": "行きたい",
    "bookmark.interested": "興味あり",
    "bookmark.remove": "削除",
    "bookmark.saved": "保存しました!",
    "bookmark.removed": "削除しました",
    "bookmark.loginRequired": "ログインして保存",
    "bookmark.mySpots": "My Spots",
    "bookmark.noBookmarks": "保存済みなし",
    "bookmark.wantToVisitEmpty": "「行きたい」スポットなし",
    "bookmark.interestedEmpty": "「興味あり」スポットなし",

    "planner.title": "AI旅行プランナー",
    "planner.desc": "保存したスポットを基にインドネシア・マレーシア旅行を計画",
    "planner.days": "旅行日数",
    "planner.daysUnit": "日",
    "planner.budget": "予算",
    "planner.budgetBudget": "節約",
    "planner.budgetModerate": "標準",
    "planner.budgetLuxury": "贅沢",
    "planner.style": "旅行スタイル",
    "planner.styleRelaxed": "ゆったり",
    "planner.styleBalanced": "バランス",
    "planner.stylePacked": "詰め込み",
    "planner.spots": "含めるスポット",
    "planner.generate": "プラン作成",
    "planner.generating": "プラン作成中...",
    "planner.result": "あなたの旅行プラン",
    "planner.retry": "再作成",
    "planner.close": "閉じる",
    "planner.noSpots": "まず「行きたい」にスポットを保存",
    "planner.error": "プラン作成に失敗。再度お試しください。",
    "planner.rateLimit": "今日の上限({limit}回)に達しました。",
    "planner.remaining": "本日残り {n} 回",
    "planner.btn": "AI旅行プラン作成",
    "planner.btnFromSpot": "このスポットでプラン",
    "planner.targetNote": "AIは「行きたい」リストのみからプランを作成します。",
    "planner.save": "プラン保存",
    "planner.saved": "プランを保存しました!",
    "planner.myPlans": "マイプラン",
    "planner.compare": "比較",
    "planner.comparePlans": "プラン比較",
    "planner.noSavedPlans": "保存済みプランなし",
    "planner.deletePlan": "削除",
    "planner.viewPlan": "表示",
    "planner.planTitle": "{days}日間プラン",
    "planner.spots_count": "{n}スポット",
    "planner.savedLocal": "この端末に保存",
    "planner.selectToCompare": "2-3 個のプランを選択して比較",
    "planner.back": "戻る",
    "planner.namePrompt": "プラン名:",
    "planner.share": "シェア",
    "planner.shareTitle": "このプランをシェア",
    "planner.copyLink": "リンクをコピー",
    "planner.sharing": "共有リンクを作成中...",

    "tips.btn": "東南アジア旅行のヒント",
    "tips.title": "インドネシア & マレーシア旅行のヒント",
    "tips.officialInfo": "日本人旅行者向けインドネシア・マレーシア旅行の実用情報。",
    "tips.visa": "ビザと入国",
    "tips.visaDesc": "インドネシア:日本旅券は到着ビザ(e-VOA, IDR 500,000)で30日滞在、1回延長可。マレーシア:日本旅券は90日ノービザ。",
    "tips.transport": "交通",
    "tips.transportInterIsland": "ID:国内線(ガルーダ/ライオン/シティリンク)、Pelniフェリー、バリ↔ギリ/ロンボク/ヌサペニダのスピードボート。MY:エアアジア、KTM ETS(ペナン↔KL↔シンガポール)、KLIA Ekspres空港鉄道。",
    "tips.transportLocal": "両国:Grabが配車の標準。IDはGojekも。メータータクシーはBluebird系のみ信頼。",
    "tips.transportBali": "バリ:バイクレンタル(約IDR 80,000/日)。KL/ペナン:モノレール、MRT、LRT — Touch'n Goカードを購入。",
    "tips.currency": "通貨と支払い",
    "tips.currencyDesc": "ID:ルピア(1 USD ≈ IDR 16,000)。MY:リンギット(1 USD ≈ MYR 4.7、100円 ≈ MYR 0.30)。現地のe-walletが主流 — ID:GoPay/OVO/DANA/QRIS、MY:Touch'n Go eWallet/GrabPay/Boost。",
    "tips.meals": "食事の価格(目安)",
    "tips.budget": "節約 — IDR 30,000 / MYR 10 (約300円)",
    "tips.budgetDesc": "ワルン、ママック、ナシゴレン、ナシレマ、ホーカー",
    "tips.moderate": "標準 — IDR 50–150k / MYR 20–60 (約500–2,000円)",
    "tips.moderateDesc": "中級レストラン、コピティアム、カフェ、フードコート",
    "tips.luxury": "贅沢 — IDR 200k+ / MYR 100+ (約3,500円〜)",
    "tips.luxuryDesc": "ファインダイニング、ビーチクラブ、バリ/KL/ペナンのホテルレストラン",
    "tips.muslim": "ムスリム旅行者へ",
    "tips.muslimDesc": "両国ともムスリム多数派。ハラル食はデフォルト。MY:スラウ(礼拝室)はどこにでもあり、JAKIMハラル認証は東南アジア最高基準。ID:モール、ガソリンスタンド、空港にムショラ。",
    "tips.weather": "天気",
    "tips.weatherDesc": "通年熱帯気候(26~32°C)。ID:乾季5~9月。MY:東海岸(クアンタン、トレンガヌ、ティオマン)の雨季は11~2月、西海岸(ペナン、ランカウイ)はより穏やか。日の出登山(ブロモ、リンジャニ、キナバル)は防寒必須。",
    "tips.useful": "便利な情報",
    "tips.bargain": "両国の伝統市場では値切りが普通 — 提示価格の30~50%から開始。",
    "tips.water": "ボトル水/濾過水のみ。MYの水道水は処理済みだが現地人も煮沸。",
    "tips.modesty": "寺院/モスク訪問時は肩と膝を覆う。寺院入口でサロンの貸出あり。",
    "tips.tipping": "チップ文化なし。MY請求書:6% SST + 10%サービス料。ID:11% PPN。",
    "tips.simcard": "ID:空港でTelkomsel/XL(IDR 100k/20GB・30日)。MY:Maxis/Celcom/Digi(RM 30–50/30日)。パスポート登録要。",
    "tips.emergency": "ID:112(共通)/110(警察)/118(救急)。MY:999(総合)/994(消防)。",
    "tips.tourist": "観光警察 — バリ:+62-361-754-599。KL:03-2149-6590。",
    "tips.korean": "在インドネシア日本国大使館:+62-21-3192-4308。在マレーシア日本国大使館:+60-3-2177-2600(KL)。",
    "tips.lastUpdated": "情報は2026年現在 · 出典:インドネシア観光省、マレーシア観光局、各航空会社公式サイト",

    "footer.text": "© 2026 Travel-ID. All rights reserved.",
    "footer.privacy": "プライバシーポリシー",
    "footer.terms": "利用規約",
  },

  ar: {
    "common.tagline": "Travel-ID",

    "seo.title": "Travel-ID — اكتشف إندونيسيا وماليزيا | بالي وكوالالمبور وما وراءها",
    "seo.description": "اكتشف أفضل الوجهات السياحية في إندونيسيا وماليزيا. بالي، يوغياكارتا، كومودو، كوالالمبور، بينانغ، لانكاوي، بورنيو والمزيد — مطاعم حلال وغرف صلاة، مخطط رحلات بالذكاء الاصطناعي.",
    "seo.keywords": "سياحة إندونيسيا, سياحة ماليزيا, بالي, كوالالمبور, بينانغ, لانكاوي, ملاكا, صباح, ساراواك, طعام حلال, سياحة إسلامية, مخطط رحلات",

    "nav.home": "الرئيسية",
    "nav.explore": "استكشاف",
    "nav.lang": "Bahasa",

    "app.title": "اكتشف إندونيسيا وماليزيا",
    "app.subtitle": "وجهات سياحية موصى بها من المجتمع",
    "app.searchPh": "ابحث عن مكان...",
    "app.catAll": "الكل",
    "app.catBeach": "شاطئ",
    "app.catTemple": "معبد",
    "app.catCultural": "ثقافي",
    "app.catVolcano": "بركان",
    "app.catNature": "طبيعة",
    "app.catDiving": "غوص",
    "app.catFood": "طعام",
    "app.catCafe": "مقهى",
    "app.catShopping": "تسوق",
    "app.catNightlife": "حياة ليلية",
    "app.catMuseum": "متحف",
    "app.catAdventure": "مغامرة",
    "app.catWellness": "عافية",
    "app.catHalal": "طعام حلال",
    "app.catMosque": "مسجد / مصلى",
    "app.catVegetarian": "نباتي",
    "app.muslimToggle": "ملائم للمسلمين",
    "app.muslimDesc": "+ مطاعم حلال وغرف صلاة (مصلى/سوراو) متضمنة",

    "prefs.title": "إعدادات السفر",
    "prefs.dietary": "التفضيلات",
    "prefs.muslim": "ملائم للمسلمين",
    "prefs.vegan": "نباتي صرف",
    "prefs.visitType": "نوع الزيارة",
    "prefs.local": "مقيم محلي (ID/MY)",
    "prefs.firstVisit": "زيارة أولى (دولية)",
    "prefs.returnVisit": "زيارة متكررة (دولية)",
    "prefs.business": "رحلة عمل",
    "prefs.group": "سفر جماعي",
    "prefs.apply": "تطبيق",

    "guide.btn": "كيفية الاستخدام",
    "guide.title": "كيفية استخدام Travel-ID",
    "guide.step1Title": "تصفح المواقع",
    "guide.step1Desc": "استكشف المواقع السياحية في إندونيسيا وماليزيا التي يوصي بها المسافرون. صفِّ حسب الفئة (شاطئ، معبد، بركان...) والمنطقة (بالي، كوالالمبور، بينانغ، كومودو...).",
    "guide.step2Title": "إعدادات السفر",
    "guide.step2Desc": "اضغط أيقونة الترس لضبط تفضيلاتك الغذائية ونوع الزيارة. تؤثر على العرض على الخريطة وتوصيات المخطط الذكي.",
    "guide.step3Title": "عرض تفاصيل الموقع",
    "guide.step3Desc": "اضغط على أي موقع لعرض الصور والوصف والعنوان وعلامات الحلال/غرفة الصلاة ورسوم الدخول. افتح الاتجاهات في خرائط Google بضغطة واحدة.",
    "guide.step4Title": "الخريطة والقائمة",
    "guide.step4Desc": "على الجوال، استخدم زر الخريطة/القائمة في الأسفل. على الحاسوب يظهران جنباً إلى جنب.",
    "guide.step5Title": "الحفظ والإشارة المرجعية",
    "guide.step5Desc": "سجل الدخول بـ Google لحفظ المواقع كـ \"أرغب بزيارته\" أو \"مهتم\". تظهر المحفوظات في قسم My Spots.",
    "guide.step6Title": "مخطط رحلات بالذكاء الاصطناعي",
    "guide.step6Desc": "بعد حفظ المواقع، افتح Plan Trip من القائمة. اختر المدة والميزانية والنمط — يبني الذكاء الاصطناعي خط سير يومي يشمل النقل بين الجزر/الدول واقتراحات الوجبات.",
    "guide.dontShowAgain": "لا تعرض مرة أخرى",
    "guide.dontShowToday": "لا تعرض اليوم",

    "about.btn": "حول",
    "about.title": "حول Travel-ID",
    "about.privacy": "سياسة الخصوصية",
    "about.terms": "شروط الخدمة",
    "about.koinfo": "",

    "app.viewMap": "خريطة",
    "app.viewList": "قائمة",
    "app.regionAll": "جميع المناطق",
    "app.regionBali": "بالي",
    "app.regionJakarta": "جاكرتا",
    "app.regionYogyakarta": "يوغياكارتا",
    "app.regionBandung": "باندونغ",
    "app.regionLombok": "لومبوك",
    "app.regionKomodo": "كومودو",
    "app.regionSurabaya": "سورابايا",
    "app.regionMedan": "ميدان",
    "app.regionBromo": "برومو",
    "app.regionBorobudur": "بوروبودور",
    "app.regionRajaAmpat": "راجا أمبات",
    "app.regionSumatra": "سومطرة",
    "app.regionSulawesi": "سولاويزي",
    "app.regionKalimantan": "كاليمانتان",
    "app.regionKL": "كوالالمبور",
    "app.regionPenang": "بينانغ",
    "app.regionLangkawi": "لانكاوي",
    "app.regionMelaka": "ملاكا",
    "app.regionSabah": "صباح (بورنيو)",
    "app.regionSarawak": "ساراواك (بورنيو)",
    "app.regionCameron": "مرتفعات كاميرون",
    "app.regionJohor": "جوهور بهرو",
    "app.regionIpoh": "إيبوه",
    "app.regionPutrajaya": "بوتراجايا",
    "app.regionOther": "أخرى",

    "app.featured": "مميَّز",
    "app.rating": "التقييم",
    "app.views": "المشاهدات",
    "app.noResults": "لا توجد نتائج. جرب فلتراً آخر.",
    "app.loading": "جاري التحميل...",
    "app.loadMore": "تحميل المزيد",
    "app.openGoogle": "فتح في خرائط Google",
    "app.mapGoogle": "خرائط Google",
    "app.website": "الموقع الرسمي",
    "app.openingHours": "ساعات العمل",
    "app.entryFee": "رسوم الدخول",
    "app.entryFeeFree": "مجاني",
    "app.bestTime": "أفضل وقت للزيارة",
    "app.localTips": "نصائح محلية",
    "app.halalBadge": "حلال",
    "app.prayerRoomBadge": "غرفة صلاة",
    "app.checkBusy": "تحقق من أوقات الازدحام في خرائط Google",
    "app.shareSpot": "شارك موقعاً",
    "app.submitTitle": "شارك موقعاً سياحياً (إندونيسيا/ماليزيا)",
    "app.submitNotice": "اقترح موقعاً للمسافرين الآخرين. سيظهر بعد مراجعة المسؤول.",
    "app.placeLabel": "اسم الموقع",
    "app.placePh": "مثال: أبراج بتروناس / تيغاللالانغ",
    "app.categoryLabel": "الفئة",
    "app.descLabel": "تقييمك",
    "app.descPh": "شارك تجربتك...",
    "app.addressLabel": "العنوان",
    "app.addressPh": "ابحث عن العنوان...",
    "app.searchBtn": "بحث",
    "app.instagramLabel": "وسوم إنستغرام",
    "app.instagramPh": "@username أو #hashtag",
    "app.authorLabel": "اسمك",
    "app.authorPh": "الاسم",
    "app.cancelBtn": "إلغاء",
    "app.submitBtn": "إرسال",
    "app.submitted": "شكراً! سيظهر بعد مراجعة المسؤول.",
    "app.submitError": "فشل الإرسال. حاول مرة أخرى.",
    "app.mapError": "تعذر تحميل الخريطة.",

    "auth.signIn": "تسجيل الدخول",
    "auth.signOut": "تسجيل الخروج",
    "auth.signInWith": "تسجيل الدخول بـ Google",
    "auth.welcome": "أهلاً وسهلاً",

    "bookmark.wantToVisit": "أرغب بزيارته",
    "bookmark.interested": "مهتم",
    "bookmark.remove": "إزالة",
    "bookmark.saved": "تم الحفظ!",
    "bookmark.removed": "تمت الإزالة",
    "bookmark.loginRequired": "سجل الدخول للحفظ",
    "bookmark.mySpots": "My Spots",
    "bookmark.noBookmarks": "لا توجد مواقع محفوظة بعد",
    "bookmark.wantToVisitEmpty": "لا توجد مواقع \"أرغب بزيارته\" بعد",
    "bookmark.interestedEmpty": "لا توجد مواقع \"مهتم\" بعد",

    "planner.title": "مخطط الرحلات بالذكاء الاصطناعي",
    "planner.desc": "خطط لرحلتك في إندونيسيا وماليزيا بناءً على المواقع المحفوظة",
    "planner.days": "مدة الرحلة",
    "planner.daysUnit": "يوم",
    "planner.budget": "الميزانية",
    "planner.budgetBudget": "اقتصادي",
    "planner.budgetModerate": "متوسط",
    "planner.budgetLuxury": "فاخر",
    "planner.style": "نمط السفر",
    "planner.styleRelaxed": "مريح",
    "planner.styleBalanced": "متوازن",
    "planner.stylePacked": "مكثف",
    "planner.spots": "المواقع المضمنة",
    "planner.generate": "إنشاء الخطة",
    "planner.generating": "جاري إنشاء خطة الرحلة...",
    "planner.result": "خطة رحلتك",
    "planner.retry": "إنشاء مجدداً",
    "planner.close": "إغلاق",
    "planner.noSpots": "احفظ المواقع كـ \"أرغب بزيارته\" أولاً",
    "planner.error": "فشل إنشاء الخطة. حاول مرة أخرى.",
    "planner.rateLimit": "تم بلوغ الحد اليومي ({limit} خطط/يوم).",
    "planner.remaining": "متبقي {n} خطط اليوم",
    "planner.btn": "أنشئ خطة سفر بالذكاء الاصطناعي",
    "planner.btnFromSpot": "خطط مع هذا الموقع",
    "planner.targetNote": "ينشئ الذكاء الاصطناعي خطط الرحلات من قائمة \"أرغب بزيارته\" فقط.",
    "planner.save": "حفظ الخطة",
    "planner.saved": "تم حفظ الخطة!",
    "planner.myPlans": "خططي",
    "planner.compare": "مقارنة",
    "planner.comparePlans": "مقارنة الخطط",
    "planner.noSavedPlans": "لا توجد خطط محفوظة",
    "planner.deletePlan": "حذف",
    "planner.viewPlan": "عرض",
    "planner.planTitle": "رحلة {days} أيام",
    "planner.spots_count": "{n} موقع",
    "planner.savedLocal": "محفوظ على هذا الجهاز",
    "planner.selectToCompare": "اختر 2-3 خطط للمقارنة",
    "planner.back": "رجوع",
    "planner.namePrompt": "اسم الخطة:",
    "planner.share": "مشاركة",
    "planner.shareTitle": "شارك هذه الخطة",
    "planner.copyLink": "نسخ الرابط",
    "planner.sharing": "جاري إنشاء رابط المشاركة...",

    "tips.btn": "نصائح السفر لجنوب شرق آسيا",
    "tips.title": "نصائح السفر — إندونيسيا وماليزيا",
    "tips.officialInfo": "إرشادات عملية للمسافرين العرب إلى إندونيسيا وماليزيا.",
    "tips.visa": "التأشيرة والدخول",
    "tips.visaDesc": "إندونيسيا: تأشيرة عند الوصول إلكترونية (e-VOA) بـ IDR 500,000 لمدة 30 يوماً قابلة للتمديد مرة واحدة. ماليزيا: دخول بدون تأشيرة لمواطني دول الخليج لمدة 30-90 يوماً (يختلف حسب الجنسية).",
    "tips.transport": "النقل",
    "tips.transportInterIsland": "إندونيسيا: رحلات داخلية (Garuda، Lion، Citilink، Batik)، عبَّارات Pelni، قوارب سريعة بين بالي والجزر. ماليزيا: AirAsia، قطار KTM ETS بينانغ↔كوالالمبور↔سنغافورة، قطار KLIA Ekspres للمطار.",
    "tips.transportLocal": "في كلا البلدين: تطبيق Grab هو السائد. إندونيسيا تضيف Gojek (طعام/دراجات أيضاً). تجنّب سيارات الأجرة بالعداد عدا Bluebird ومماثلاتها.",
    "tips.transportBali": "بالي: استئجار دراجة نارية بنحو IDR 80,000/يوم. كوالالمبور/بينانغ: المونوريل، MRT، LRT تغطي المدينة — اشترِ بطاقة Touch'n Go.",
    "tips.currency": "العملة والدفع",
    "tips.currencyDesc": "إندونيسيا: روبية إندونيسية (1 USD ≈ IDR 16,000). ماليزيا: رينغيت (1 USD ≈ MYR 4.7). المحافظ الرقمية المحلية مهيمنة — GoPay/OVO/DANA/QRIS في إندونيسيا؛ Touch'n Go eWallet/GrabPay/Boost في ماليزيا.",
    "tips.meals": "أسعار الوجبات (تقريبية)",
    "tips.budget": "اقتصادي — IDR 30,000 / MYR 10",
    "tips.budgetDesc": "وارونغ، مطاعم مامك، نازي بادانغ، نازي ليماك، مراكز الباعة المتجولين",
    "tips.moderate": "متوسط — IDR 50–150k / MYR 20–60",
    "tips.moderateDesc": "مطاعم متوسطة، كوبيتيام، مقاهٍ، صالات الطعام في المراكز التجارية",
    "tips.luxury": "فاخر — IDR 200k+ / MYR 100+",
    "tips.luxuryDesc": "مطاعم راقية، نوادي شاطئية، مطاعم فنادق في بالي/كوالالمبور/بينانغ",
    "tips.muslim": "للمسافرين المسلمين",
    "tips.muslimDesc": "كلا البلدين بأغلبية مسلمة. الطعام الحلال هو الأصل. ماليزيا: شهادة JAKIM للحلال هي المعيار الأكثر صرامة في جنوب شرق آسيا. إندونيسيا: غرف الصلاة (المصلى) متوفرة في المراكز التجارية ومحطات الوقود والمطارات. صلاة الجمعة (12:00) قد تبطئ الخدمة في المناطق غير السياحية.",
    "tips.weather": "الطقس",
    "tips.weatherDesc": "استوائي طوال العام (26-32°م). موسم الجفاف في إندونيسيا من مايو إلى سبتمبر. ماليزيا لها موسمان للأمطار: الساحل الشرقي (كوانتان، ترينغانو، تيومان) من نوفمبر إلى فبراير؛ الساحل الغربي (بينانغ، لانكاوي) ألطف. صعود الجبال عند الفجر (برومو، رينجاني، كينابالو) يتطلب طبقات دافئة.",
    "tips.useful": "نصائح مفيدة",
    "tips.bargain": "المساومة متوقَّعة في الأسواق التقليدية في كلا البلدين — ابدأ بـ 30-50% من السعر المطلوب.",
    "tips.water": "اشرب فقط الماء المعبأ أو المرشَّح. ماء الصنبور في ماليزيا معالَج لكنه يُغلى محلياً.",
    "tips.modesty": "غطِّ الكتفين والركبتين عند زيارة المعابد والمساجد. تتوفر السارونغ عند مدخل المعابد عادة.",
    "tips.tipping": "البقشيش غير معتاد. ماليزيا تضيف 6% SST + 10% خدمة. إندونيسيا تضيف 11% PPN.",
    "tips.simcard": "إندونيسيا: Telkomsel/XL في المطار (IDR 100,000 لـ 20 جيجا/30 يوم). ماليزيا: Maxis/Celcom/Digi (MYR 30-50 لـ 30 يوم). جواز السفر مطلوب للتسجيل.",
    "tips.emergency": "إندونيسيا: 112 (عام) / 110 (شرطة) / 118 (إسعاف). ماليزيا: 999 (للجميع) / 994 (إطفاء).",
    "tips.tourist": "شرطة السياحة — بالي: +62-361-754-599. كوالالمبور: 03-2149-6590.",
    "tips.lastUpdated": "المعلومات حتى عام 2026 · المصادر: وزارة السياحة الإندونيسية، السياحة الماليزية، مواقع شركات الطيران الرسمية",

    "footer.text": "© 2026 Travel-ID. جميع الحقوق محفوظة.",
    "footer.privacy": "سياسة الخصوصية",
    "footer.terms": "شروط الخدمة",
  }
};

// Backward compat aliases
translations['zh-CN'] = translations.zh;
translations['zh-cn'] = translations.zh;
translations['ms-MY'] = translations.ms;
translations['ar-SA'] = translations.ar;
translations['ar-AE'] = translations.ar;

if (typeof module !== 'undefined' && module.exports) {
  module.exports = translations;
} else if (typeof window !== 'undefined') {
  window.__TRAVEL_TRANSLATIONS__ = translations;
}
